//   Ordt 190617.01 autogenerated file 
//   Input: /home/shareef/git/cocotb-regfile/rdl/regfile.rdl.pp.final
//   Parms: /home/shareef/git/cocotb-regfile/rdl/rdl.params
//   Date: Fri Jun 28 12:46:33 BST 2019
//

//
//---------- module regfile_addr_map_pio
//
module regfile_addr_map_pio
(
  clk,
  sig_reset_n,
  h2l__user_irq_flags__irq_0__user_irq_0_intr,
  h2l__user_irq_flags__irq_0__user_irq_1_intr,
  h2l__user_irq_flags__irq_0__user_irq_2_intr,
  h2l__user_irq_flags__irq_0__user_irq_3_intr,
  h2l__user_irq_flags__irq_0__user_irq_4_intr,
  h2l__user_irq_flags__irq_0__user_irq_5_intr,
  h2l__user_irq_flags__irq_0__user_irq_6_intr,
  h2l__user_irq_flags__irq_0__user_irq_7_intr,
  h2l__user_irq_flags__irq_1__user_irq_0_intr,
  h2l__user_irq_flags__irq_1__user_irq_1_intr,
  h2l__user_irq_flags__irq_1__user_irq_2_intr,
  h2l__user_irq_flags__irq_1__user_irq_3_intr,
  h2l__user_irq_flags__irq_1__user_irq_4_intr,
  h2l__user_irq_flags__irq_1__user_irq_5_intr,
  h2l__user_irq_flags__irq_1__user_irq_6_intr,
  h2l__user_irq_flags__irq_1__user_irq_7_intr,
  h2l__user_irq_flags__irq_2__user_irq_0_intr,
  h2l__user_irq_flags__irq_2__user_irq_1_intr,
  h2l__user_irq_flags__irq_2__user_irq_2_intr,
  h2l__user_irq_flags__irq_2__user_irq_3_intr,
  h2l__user_irq_flags__irq_2__user_irq_4_intr,
  h2l__user_irq_flags__irq_2__user_irq_5_intr,
  h2l__user_irq_flags__irq_2__user_irq_6_intr,
  h2l__user_irq_flags__irq_2__user_irq_7_intr,
  h2l__user_irq_flags__irq_3__user_irq_0_intr,
  h2l__user_irq_flags__irq_3__user_irq_1_intr,
  h2l__user_irq_flags__irq_3__user_irq_2_intr,
  h2l__user_irq_flags__irq_3__user_irq_3_intr,
  h2l__user_irq_flags__irq_3__user_irq_4_intr,
  h2l__user_irq_flags__irq_3__user_irq_5_intr,
  h2l__user_irq_flags__irq_3__user_irq_6_intr,
  h2l__user_irq_flags__irq_3__user_irq_7_intr,
  h2l__user_irq_flags__irq_4__user_irq_0_intr,
  h2l__user_irq_flags__irq_4__user_irq_1_intr,
  h2l__user_irq_flags__irq_4__user_irq_2_intr,
  h2l__user_irq_flags__irq_4__user_irq_3_intr,
  h2l__user_irq_flags__irq_4__user_irq_4_intr,
  h2l__user_irq_flags__irq_4__user_irq_5_intr,
  h2l__user_irq_flags__irq_4__user_irq_6_intr,
  h2l__user_irq_flags__irq_4__user_irq_7_intr,
  h2l__user_irq_flags__irq_5__user_irq_0_intr,
  h2l__user_irq_flags__irq_5__user_irq_1_intr,
  h2l__user_irq_flags__irq_5__user_irq_2_intr,
  h2l__user_irq_flags__irq_5__user_irq_3_intr,
  h2l__user_irq_flags__irq_5__user_irq_4_intr,
  h2l__user_irq_flags__irq_5__user_irq_5_intr,
  h2l__user_irq_flags__irq_5__user_irq_6_intr,
  h2l__user_irq_flags__irq_5__user_irq_7_intr,
  h2l__user_irq_flags__irq_6__user_irq_0_intr,
  h2l__user_irq_flags__irq_6__user_irq_1_intr,
  h2l__user_irq_flags__irq_6__user_irq_2_intr,
  h2l__user_irq_flags__irq_6__user_irq_3_intr,
  h2l__user_irq_flags__irq_6__user_irq_4_intr,
  h2l__user_irq_flags__irq_6__user_irq_5_intr,
  h2l__user_irq_flags__irq_6__user_irq_6_intr,
  h2l__user_irq_flags__irq_6__user_irq_7_intr,
  h2l__user_irq_flags__irq_7__user_irq_0_intr,
  h2l__user_irq_flags__irq_7__user_irq_1_intr,
  h2l__user_irq_flags__irq_7__user_irq_2_intr,
  h2l__user_irq_flags__irq_7__user_irq_3_intr,
  h2l__user_irq_flags__irq_7__user_irq_4_intr,
  h2l__user_irq_flags__irq_7__user_irq_5_intr,
  h2l__user_irq_flags__irq_7__user_irq_6_intr,
  h2l__user_irq_flags__irq_7__user_irq_7_intr,
  h2l__user_irq_flags__irq_8__user_irq_0_intr,
  h2l__user_irq_flags__irq_8__user_irq_1_intr,
  h2l__user_irq_flags__irq_8__user_irq_2_intr,
  h2l__user_irq_flags__irq_8__user_irq_3_intr,
  h2l__user_irq_flags__irq_8__user_irq_4_intr,
  h2l__user_irq_flags__irq_8__user_irq_5_intr,
  h2l__user_irq_flags__irq_8__user_irq_6_intr,
  h2l__user_irq_flags__irq_8__user_irq_7_intr,
  h2l__user_irq_flags__irq_9__user_irq_0_intr,
  h2l__user_irq_flags__irq_9__user_irq_1_intr,
  h2l__user_irq_flags__irq_9__user_irq_2_intr,
  h2l__user_irq_flags__irq_9__user_irq_3_intr,
  h2l__user_irq_flags__irq_9__user_irq_4_intr,
  h2l__user_irq_flags__irq_9__user_irq_5_intr,
  h2l__user_irq_flags__irq_9__user_irq_6_intr,
  h2l__user_irq_flags__irq_9__user_irq_7_intr,
  h2l__user_irq_flags__irq_10__user_irq_0_intr,
  h2l__user_irq_flags__irq_10__user_irq_1_intr,
  h2l__user_irq_flags__irq_10__user_irq_2_intr,
  h2l__user_irq_flags__irq_10__user_irq_3_intr,
  h2l__user_irq_flags__irq_10__user_irq_4_intr,
  h2l__user_irq_flags__irq_10__user_irq_5_intr,
  h2l__user_irq_flags__irq_10__user_irq_6_intr,
  h2l__user_irq_flags__irq_10__user_irq_7_intr,
  h2l__user_irq_flags__irq_11__user_irq_0_intr,
  h2l__user_irq_flags__irq_11__user_irq_1_intr,
  h2l__user_irq_flags__irq_11__user_irq_2_intr,
  h2l__user_irq_flags__irq_11__user_irq_3_intr,
  h2l__user_irq_flags__irq_11__user_irq_4_intr,
  h2l__user_irq_flags__irq_11__user_irq_5_intr,
  h2l__user_irq_flags__irq_11__user_irq_6_intr,
  h2l__user_irq_flags__irq_11__user_irq_7_intr,
  h2l__user_irq_flags__irq_12__user_irq_0_intr,
  h2l__user_irq_flags__irq_12__user_irq_1_intr,
  h2l__user_irq_flags__irq_12__user_irq_2_intr,
  h2l__user_irq_flags__irq_12__user_irq_3_intr,
  h2l__user_irq_flags__irq_12__user_irq_4_intr,
  h2l__user_irq_flags__irq_12__user_irq_5_intr,
  h2l__user_irq_flags__irq_12__user_irq_6_intr,
  h2l__user_irq_flags__irq_12__user_irq_7_intr,
  h2l__user_irq_flags__irq_13__user_irq_0_intr,
  h2l__user_irq_flags__irq_13__user_irq_1_intr,
  h2l__user_irq_flags__irq_13__user_irq_2_intr,
  h2l__user_irq_flags__irq_13__user_irq_3_intr,
  h2l__user_irq_flags__irq_13__user_irq_4_intr,
  h2l__user_irq_flags__irq_13__user_irq_5_intr,
  h2l__user_irq_flags__irq_13__user_irq_6_intr,
  h2l__user_irq_flags__irq_13__user_irq_7_intr,
  h2l__user_irq_flags__irq_14__user_irq_0_intr,
  h2l__user_irq_flags__irq_14__user_irq_1_intr,
  h2l__user_irq_flags__irq_14__user_irq_2_intr,
  h2l__user_irq_flags__irq_14__user_irq_3_intr,
  h2l__user_irq_flags__irq_14__user_irq_4_intr,
  h2l__user_irq_flags__irq_14__user_irq_5_intr,
  h2l__user_irq_flags__irq_14__user_irq_6_intr,
  h2l__user_irq_flags__irq_14__user_irq_7_intr,
  h2l__user_irq_flags__irq_15__user_irq_0_intr,
  h2l__user_irq_flags__irq_15__user_irq_1_intr,
  h2l__user_irq_flags__irq_15__user_irq_2_intr,
  h2l__user_irq_flags__irq_15__user_irq_3_intr,
  h2l__user_irq_flags__irq_15__user_irq_4_intr,
  h2l__user_irq_flags__irq_15__user_irq_5_intr,
  h2l__user_irq_flags__irq_15__user_irq_6_intr,
  h2l__user_irq_flags__irq_15__user_irq_7_intr,
  h2l__user_stat_regs__user_stat_0_user_stat_w,
  h2l__user_stat_regs__user_stat_0_user_stat_we,
  h2l__user_stat_regs__user_stat_1_user_stat_w,
  h2l__user_stat_regs__user_stat_1_user_stat_we,
  h2l__user_stat_regs__user_stat_2_user_stat_w,
  h2l__user_stat_regs__user_stat_2_user_stat_we,
  h2l__user_stat_regs__user_stat_3_user_stat_w,
  h2l__user_stat_regs__user_stat_3_user_stat_we,
  h2l__user_stat_regs__user_stat_4_user_stat_w,
  h2l__user_stat_regs__user_stat_4_user_stat_we,
  h2l__user_stat_regs__user_stat_5_user_stat_w,
  h2l__user_stat_regs__user_stat_5_user_stat_we,
  h2d_pio_dec_address,
  h2d_pio_dec_write_data,
  h2d_pio_dec_trans_size,
  h2d_pio_dec_write,
  h2d_pio_dec_read,

  l2h__status_intr_o,
  l2h__user_irq_status_intr_o,
  l2h__user_irq_flags__irq_0_intr_o,
  l2h__user_irq_flags__irq_1_intr_o,
  l2h__user_irq_flags__irq_2_intr_o,
  l2h__user_irq_flags__irq_3_intr_o,
  l2h__user_irq_flags__irq_4_intr_o,
  l2h__user_irq_flags__irq_5_intr_o,
  l2h__user_irq_flags__irq_6_intr_o,
  l2h__user_irq_flags__irq_7_intr_o,
  l2h__user_irq_flags__irq_8_intr_o,
  l2h__user_irq_flags__irq_9_intr_o,
  l2h__user_irq_flags__irq_10_intr_o,
  l2h__user_irq_flags__irq_11_intr_o,
  l2h__user_irq_flags__irq_12_intr_o,
  l2h__user_irq_flags__irq_13_intr_o,
  l2h__user_irq_flags__irq_14_intr_o,
  l2h__user_irq_flags__irq_15_intr_o,
  l2h__user_cfg_regs__user_cfg_0_user_cfg_r,
  l2h__user_cfg_regs__user_cfg_1_user_cfg_r,
  l2h__user_cfg_regs__user_cfg_2_user_cfg_r,
  l2h__user_cfg_regs__user_cfg_3_user_cfg_r,
  d2h_dec_pio_trans_size,
  d2h_dec_pio_read_data,
  d2h_dec_pio_ack,
  d2h_dec_pio_nack );

  //------- inputs
  input    clk;
  input    sig_reset_n;
  input    h2l__user_irq_flags__irq_0__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_0__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_1__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_2__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_3__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_4__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_5__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_6__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_7__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_8__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_9__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_10__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_11__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_12__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_13__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_14__user_irq_7_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_0_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_1_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_2_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_3_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_4_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_5_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_6_intr;
  input    h2l__user_irq_flags__irq_15__user_irq_7_intr;
  input     [15:0] h2l__user_stat_regs__user_stat_0_user_stat_w;
  input    h2l__user_stat_regs__user_stat_0_user_stat_we;
  input     [15:0] h2l__user_stat_regs__user_stat_1_user_stat_w;
  input    h2l__user_stat_regs__user_stat_1_user_stat_we;
  input     [15:0] h2l__user_stat_regs__user_stat_2_user_stat_w;
  input    h2l__user_stat_regs__user_stat_2_user_stat_we;
  input     [15:0] h2l__user_stat_regs__user_stat_3_user_stat_w;
  input    h2l__user_stat_regs__user_stat_3_user_stat_we;
  input     [15:0] h2l__user_stat_regs__user_stat_4_user_stat_w;
  input    h2l__user_stat_regs__user_stat_4_user_stat_we;
  input     [15:0] h2l__user_stat_regs__user_stat_5_user_stat_w;
  input    h2l__user_stat_regs__user_stat_5_user_stat_we;
  input     [8:0] h2d_pio_dec_address;
  input     [15:0] h2d_pio_dec_write_data;
  input    h2d_pio_dec_trans_size;
  input    h2d_pio_dec_write;
  input    h2d_pio_dec_read;

  //------- outputs
  output    l2h__status_intr_o;
  output    l2h__user_irq_status_intr_o;
  output    l2h__user_irq_flags__irq_0_intr_o;
  output    l2h__user_irq_flags__irq_1_intr_o;
  output    l2h__user_irq_flags__irq_2_intr_o;
  output    l2h__user_irq_flags__irq_3_intr_o;
  output    l2h__user_irq_flags__irq_4_intr_o;
  output    l2h__user_irq_flags__irq_5_intr_o;
  output    l2h__user_irq_flags__irq_6_intr_o;
  output    l2h__user_irq_flags__irq_7_intr_o;
  output    l2h__user_irq_flags__irq_8_intr_o;
  output    l2h__user_irq_flags__irq_9_intr_o;
  output    l2h__user_irq_flags__irq_10_intr_o;
  output    l2h__user_irq_flags__irq_11_intr_o;
  output    l2h__user_irq_flags__irq_12_intr_o;
  output    l2h__user_irq_flags__irq_13_intr_o;
  output    l2h__user_irq_flags__irq_14_intr_o;
  output    l2h__user_irq_flags__irq_15_intr_o;
  output     [15:0] l2h__user_cfg_regs__user_cfg_0_user_cfg_r;
  output     [15:0] l2h__user_cfg_regs__user_cfg_1_user_cfg_r;
  output     [15:0] l2h__user_cfg_regs__user_cfg_2_user_cfg_r;
  output     [15:0] l2h__user_cfg_regs__user_cfg_3_user_cfg_r;
  output    d2h_dec_pio_trans_size;
  output     [15:0] d2h_dec_pio_read_data;
  output    d2h_dec_pio_ack;
  output    d2h_dec_pio_nack;


  //------- wire defines
  wire   [15:0] d2l__control_w;
  wire  d2l__control_we;
  wire  d2l__control_re;
  wire   [15:0] d2l__status_w;
  wire  d2l__status_we;
  wire  d2l__status_re;
  wire   [15:0] d2l__user_irq_status_w;
  wire  d2l__user_irq_status_we;
  wire  d2l__user_irq_status_re;
  wire   [15:0] d2l__user_irq_enable_w;
  wire  d2l__user_irq_enable_we;
  wire  d2l__user_irq_enable_re;
  wire   [15:0] d2l__user_irq_flags__irq_0_w;
  wire  d2l__user_irq_flags__irq_0_we;
  wire  d2l__user_irq_flags__irq_0_re;
  wire   [15:0] d2l__user_irq_flags__irq_1_w;
  wire  d2l__user_irq_flags__irq_1_we;
  wire  d2l__user_irq_flags__irq_1_re;
  wire   [15:0] d2l__user_irq_flags__irq_2_w;
  wire  d2l__user_irq_flags__irq_2_we;
  wire  d2l__user_irq_flags__irq_2_re;
  wire   [15:0] d2l__user_irq_flags__irq_3_w;
  wire  d2l__user_irq_flags__irq_3_we;
  wire  d2l__user_irq_flags__irq_3_re;
  wire   [15:0] d2l__user_irq_flags__irq_4_w;
  wire  d2l__user_irq_flags__irq_4_we;
  wire  d2l__user_irq_flags__irq_4_re;
  wire   [15:0] d2l__user_irq_flags__irq_5_w;
  wire  d2l__user_irq_flags__irq_5_we;
  wire  d2l__user_irq_flags__irq_5_re;
  wire   [15:0] d2l__user_irq_flags__irq_6_w;
  wire  d2l__user_irq_flags__irq_6_we;
  wire  d2l__user_irq_flags__irq_6_re;
  wire   [15:0] d2l__user_irq_flags__irq_7_w;
  wire  d2l__user_irq_flags__irq_7_we;
  wire  d2l__user_irq_flags__irq_7_re;
  wire   [15:0] d2l__user_irq_flags__irq_8_w;
  wire  d2l__user_irq_flags__irq_8_we;
  wire  d2l__user_irq_flags__irq_8_re;
  wire   [15:0] d2l__user_irq_flags__irq_9_w;
  wire  d2l__user_irq_flags__irq_9_we;
  wire  d2l__user_irq_flags__irq_9_re;
  wire   [15:0] d2l__user_irq_flags__irq_10_w;
  wire  d2l__user_irq_flags__irq_10_we;
  wire  d2l__user_irq_flags__irq_10_re;
  wire   [15:0] d2l__user_irq_flags__irq_11_w;
  wire  d2l__user_irq_flags__irq_11_we;
  wire  d2l__user_irq_flags__irq_11_re;
  wire   [15:0] d2l__user_irq_flags__irq_12_w;
  wire  d2l__user_irq_flags__irq_12_we;
  wire  d2l__user_irq_flags__irq_12_re;
  wire   [15:0] d2l__user_irq_flags__irq_13_w;
  wire  d2l__user_irq_flags__irq_13_we;
  wire  d2l__user_irq_flags__irq_13_re;
  wire   [15:0] d2l__user_irq_flags__irq_14_w;
  wire  d2l__user_irq_flags__irq_14_we;
  wire  d2l__user_irq_flags__irq_14_re;
  wire   [15:0] d2l__user_irq_flags__irq_15_w;
  wire  d2l__user_irq_flags__irq_15_we;
  wire  d2l__user_irq_flags__irq_15_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_0_w;
  wire  d2l__user_irq_en_flags__irq_en_0_we;
  wire  d2l__user_irq_en_flags__irq_en_0_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_1_w;
  wire  d2l__user_irq_en_flags__irq_en_1_we;
  wire  d2l__user_irq_en_flags__irq_en_1_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_2_w;
  wire  d2l__user_irq_en_flags__irq_en_2_we;
  wire  d2l__user_irq_en_flags__irq_en_2_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_3_w;
  wire  d2l__user_irq_en_flags__irq_en_3_we;
  wire  d2l__user_irq_en_flags__irq_en_3_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_4_w;
  wire  d2l__user_irq_en_flags__irq_en_4_we;
  wire  d2l__user_irq_en_flags__irq_en_4_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_5_w;
  wire  d2l__user_irq_en_flags__irq_en_5_we;
  wire  d2l__user_irq_en_flags__irq_en_5_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_6_w;
  wire  d2l__user_irq_en_flags__irq_en_6_we;
  wire  d2l__user_irq_en_flags__irq_en_6_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_7_w;
  wire  d2l__user_irq_en_flags__irq_en_7_we;
  wire  d2l__user_irq_en_flags__irq_en_7_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_8_w;
  wire  d2l__user_irq_en_flags__irq_en_8_we;
  wire  d2l__user_irq_en_flags__irq_en_8_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_9_w;
  wire  d2l__user_irq_en_flags__irq_en_9_we;
  wire  d2l__user_irq_en_flags__irq_en_9_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_10_w;
  wire  d2l__user_irq_en_flags__irq_en_10_we;
  wire  d2l__user_irq_en_flags__irq_en_10_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_11_w;
  wire  d2l__user_irq_en_flags__irq_en_11_we;
  wire  d2l__user_irq_en_flags__irq_en_11_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_12_w;
  wire  d2l__user_irq_en_flags__irq_en_12_we;
  wire  d2l__user_irq_en_flags__irq_en_12_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_13_w;
  wire  d2l__user_irq_en_flags__irq_en_13_we;
  wire  d2l__user_irq_en_flags__irq_en_13_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_14_w;
  wire  d2l__user_irq_en_flags__irq_en_14_we;
  wire  d2l__user_irq_en_flags__irq_en_14_re;
  wire   [15:0] d2l__user_irq_en_flags__irq_en_15_w;
  wire  d2l__user_irq_en_flags__irq_en_15_we;
  wire  d2l__user_irq_en_flags__irq_en_15_re;
  wire   [15:0] d2l__user_cfg_regs__user_cfg_0_w;
  wire  d2l__user_cfg_regs__user_cfg_0_we;
  wire  d2l__user_cfg_regs__user_cfg_0_re;
  wire   [15:0] d2l__user_cfg_regs__user_cfg_1_w;
  wire  d2l__user_cfg_regs__user_cfg_1_we;
  wire  d2l__user_cfg_regs__user_cfg_1_re;
  wire   [15:0] d2l__user_cfg_regs__user_cfg_2_w;
  wire  d2l__user_cfg_regs__user_cfg_2_we;
  wire  d2l__user_cfg_regs__user_cfg_2_re;
  wire   [15:0] d2l__user_cfg_regs__user_cfg_3_w;
  wire  d2l__user_cfg_regs__user_cfg_3_we;
  wire  d2l__user_cfg_regs__user_cfg_3_re;
  wire   [15:0] d2l__user_stat_regs__user_stat_0_w;
  wire  d2l__user_stat_regs__user_stat_0_we;
  wire  d2l__user_stat_regs__user_stat_0_re;
  wire   [15:0] d2l__user_stat_regs__user_stat_1_w;
  wire  d2l__user_stat_regs__user_stat_1_we;
  wire  d2l__user_stat_regs__user_stat_1_re;
  wire   [15:0] d2l__user_stat_regs__user_stat_2_w;
  wire  d2l__user_stat_regs__user_stat_2_we;
  wire  d2l__user_stat_regs__user_stat_2_re;
  wire   [15:0] d2l__user_stat_regs__user_stat_3_w;
  wire  d2l__user_stat_regs__user_stat_3_we;
  wire  d2l__user_stat_regs__user_stat_3_re;
  wire   [15:0] d2l__user_stat_regs__user_stat_4_w;
  wire  d2l__user_stat_regs__user_stat_4_we;
  wire  d2l__user_stat_regs__user_stat_4_re;
  wire   [15:0] d2l__user_stat_regs__user_stat_5_w;
  wire  d2l__user_stat_regs__user_stat_5_we;
  wire  d2l__user_stat_regs__user_stat_5_re;
  wire   [15:0] l2d__control_r;
  wire   [15:0] l2d__status_r;
  wire   [15:0] l2d__user_irq_status_r;
  wire   [15:0] l2d__user_irq_enable_r;
  wire   [15:0] l2d__user_irq_flags__irq_0_r;
  wire   [15:0] l2d__user_irq_flags__irq_1_r;
  wire   [15:0] l2d__user_irq_flags__irq_2_r;
  wire   [15:0] l2d__user_irq_flags__irq_3_r;
  wire   [15:0] l2d__user_irq_flags__irq_4_r;
  wire   [15:0] l2d__user_irq_flags__irq_5_r;
  wire   [15:0] l2d__user_irq_flags__irq_6_r;
  wire   [15:0] l2d__user_irq_flags__irq_7_r;
  wire   [15:0] l2d__user_irq_flags__irq_8_r;
  wire   [15:0] l2d__user_irq_flags__irq_9_r;
  wire   [15:0] l2d__user_irq_flags__irq_10_r;
  wire   [15:0] l2d__user_irq_flags__irq_11_r;
  wire   [15:0] l2d__user_irq_flags__irq_12_r;
  wire   [15:0] l2d__user_irq_flags__irq_13_r;
  wire   [15:0] l2d__user_irq_flags__irq_14_r;
  wire   [15:0] l2d__user_irq_flags__irq_15_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_0_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_1_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_2_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_3_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_4_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_5_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_6_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_7_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_8_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_9_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_10_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_11_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_12_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_13_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_14_r;
  wire   [15:0] l2d__user_irq_en_flags__irq_en_15_r;
  wire   [15:0] l2d__user_cfg_regs__user_cfg_0_r;
  wire   [15:0] l2d__user_cfg_regs__user_cfg_1_r;
  wire   [15:0] l2d__user_cfg_regs__user_cfg_2_r;
  wire   [15:0] l2d__user_cfg_regs__user_cfg_3_r;
  wire   [15:0] l2d__user_stat_regs__user_stat_0_r;
  wire   [15:0] l2d__user_stat_regs__user_stat_1_r;
  wire   [15:0] l2d__user_stat_regs__user_stat_2_r;
  wire   [15:0] l2d__user_stat_regs__user_stat_3_r;
  wire   [15:0] l2d__user_stat_regs__user_stat_4_r;
  wire   [15:0] l2d__user_stat_regs__user_stat_5_r;
  
  
  regfile_addr_map_jrdl_decode pio_decode (
    .clk(clk),
    .sig_reset_n(sig_reset_n),
    .h2d_pio_dec_address(h2d_pio_dec_address),
    .h2d_pio_dec_write_data(h2d_pio_dec_write_data),
    .h2d_pio_dec_trans_size(h2d_pio_dec_trans_size),
    .h2d_pio_dec_write(h2d_pio_dec_write),
    .h2d_pio_dec_read(h2d_pio_dec_read),
    .l2d__control_r(l2d__control_r),
    .l2d__status_r(l2d__status_r),
    .l2d__user_irq_status_r(l2d__user_irq_status_r),
    .l2d__user_irq_enable_r(l2d__user_irq_enable_r),
    .l2d__user_irq_flags__irq_0_r(l2d__user_irq_flags__irq_0_r),
    .l2d__user_irq_flags__irq_1_r(l2d__user_irq_flags__irq_1_r),
    .l2d__user_irq_flags__irq_2_r(l2d__user_irq_flags__irq_2_r),
    .l2d__user_irq_flags__irq_3_r(l2d__user_irq_flags__irq_3_r),
    .l2d__user_irq_flags__irq_4_r(l2d__user_irq_flags__irq_4_r),
    .l2d__user_irq_flags__irq_5_r(l2d__user_irq_flags__irq_5_r),
    .l2d__user_irq_flags__irq_6_r(l2d__user_irq_flags__irq_6_r),
    .l2d__user_irq_flags__irq_7_r(l2d__user_irq_flags__irq_7_r),
    .l2d__user_irq_flags__irq_8_r(l2d__user_irq_flags__irq_8_r),
    .l2d__user_irq_flags__irq_9_r(l2d__user_irq_flags__irq_9_r),
    .l2d__user_irq_flags__irq_10_r(l2d__user_irq_flags__irq_10_r),
    .l2d__user_irq_flags__irq_11_r(l2d__user_irq_flags__irq_11_r),
    .l2d__user_irq_flags__irq_12_r(l2d__user_irq_flags__irq_12_r),
    .l2d__user_irq_flags__irq_13_r(l2d__user_irq_flags__irq_13_r),
    .l2d__user_irq_flags__irq_14_r(l2d__user_irq_flags__irq_14_r),
    .l2d__user_irq_flags__irq_15_r(l2d__user_irq_flags__irq_15_r),
    .l2d__user_irq_en_flags__irq_en_0_r(l2d__user_irq_en_flags__irq_en_0_r),
    .l2d__user_irq_en_flags__irq_en_1_r(l2d__user_irq_en_flags__irq_en_1_r),
    .l2d__user_irq_en_flags__irq_en_2_r(l2d__user_irq_en_flags__irq_en_2_r),
    .l2d__user_irq_en_flags__irq_en_3_r(l2d__user_irq_en_flags__irq_en_3_r),
    .l2d__user_irq_en_flags__irq_en_4_r(l2d__user_irq_en_flags__irq_en_4_r),
    .l2d__user_irq_en_flags__irq_en_5_r(l2d__user_irq_en_flags__irq_en_5_r),
    .l2d__user_irq_en_flags__irq_en_6_r(l2d__user_irq_en_flags__irq_en_6_r),
    .l2d__user_irq_en_flags__irq_en_7_r(l2d__user_irq_en_flags__irq_en_7_r),
    .l2d__user_irq_en_flags__irq_en_8_r(l2d__user_irq_en_flags__irq_en_8_r),
    .l2d__user_irq_en_flags__irq_en_9_r(l2d__user_irq_en_flags__irq_en_9_r),
    .l2d__user_irq_en_flags__irq_en_10_r(l2d__user_irq_en_flags__irq_en_10_r),
    .l2d__user_irq_en_flags__irq_en_11_r(l2d__user_irq_en_flags__irq_en_11_r),
    .l2d__user_irq_en_flags__irq_en_12_r(l2d__user_irq_en_flags__irq_en_12_r),
    .l2d__user_irq_en_flags__irq_en_13_r(l2d__user_irq_en_flags__irq_en_13_r),
    .l2d__user_irq_en_flags__irq_en_14_r(l2d__user_irq_en_flags__irq_en_14_r),
    .l2d__user_irq_en_flags__irq_en_15_r(l2d__user_irq_en_flags__irq_en_15_r),
    .l2d__user_cfg_regs__user_cfg_0_r(l2d__user_cfg_regs__user_cfg_0_r),
    .l2d__user_cfg_regs__user_cfg_1_r(l2d__user_cfg_regs__user_cfg_1_r),
    .l2d__user_cfg_regs__user_cfg_2_r(l2d__user_cfg_regs__user_cfg_2_r),
    .l2d__user_cfg_regs__user_cfg_3_r(l2d__user_cfg_regs__user_cfg_3_r),
    .l2d__user_stat_regs__user_stat_0_r(l2d__user_stat_regs__user_stat_0_r),
    .l2d__user_stat_regs__user_stat_1_r(l2d__user_stat_regs__user_stat_1_r),
    .l2d__user_stat_regs__user_stat_2_r(l2d__user_stat_regs__user_stat_2_r),
    .l2d__user_stat_regs__user_stat_3_r(l2d__user_stat_regs__user_stat_3_r),
    .l2d__user_stat_regs__user_stat_4_r(l2d__user_stat_regs__user_stat_4_r),
    .l2d__user_stat_regs__user_stat_5_r(l2d__user_stat_regs__user_stat_5_r),
    .d2h_dec_pio_trans_size(d2h_dec_pio_trans_size),
    .d2h_dec_pio_read_data(d2h_dec_pio_read_data),
    .d2h_dec_pio_ack(d2h_dec_pio_ack),
    .d2h_dec_pio_nack(d2h_dec_pio_nack),
    .d2l__control_w(d2l__control_w),
    .d2l__control_we(d2l__control_we),
    .d2l__control_re(d2l__control_re),
    .d2l__status_w(d2l__status_w),
    .d2l__status_we(d2l__status_we),
    .d2l__status_re(d2l__status_re),
    .d2l__user_irq_status_w(d2l__user_irq_status_w),
    .d2l__user_irq_status_we(d2l__user_irq_status_we),
    .d2l__user_irq_status_re(d2l__user_irq_status_re),
    .d2l__user_irq_enable_w(d2l__user_irq_enable_w),
    .d2l__user_irq_enable_we(d2l__user_irq_enable_we),
    .d2l__user_irq_enable_re(d2l__user_irq_enable_re),
    .d2l__user_irq_flags__irq_0_w(d2l__user_irq_flags__irq_0_w),
    .d2l__user_irq_flags__irq_0_we(d2l__user_irq_flags__irq_0_we),
    .d2l__user_irq_flags__irq_0_re(d2l__user_irq_flags__irq_0_re),
    .d2l__user_irq_flags__irq_1_w(d2l__user_irq_flags__irq_1_w),
    .d2l__user_irq_flags__irq_1_we(d2l__user_irq_flags__irq_1_we),
    .d2l__user_irq_flags__irq_1_re(d2l__user_irq_flags__irq_1_re),
    .d2l__user_irq_flags__irq_2_w(d2l__user_irq_flags__irq_2_w),
    .d2l__user_irq_flags__irq_2_we(d2l__user_irq_flags__irq_2_we),
    .d2l__user_irq_flags__irq_2_re(d2l__user_irq_flags__irq_2_re),
    .d2l__user_irq_flags__irq_3_w(d2l__user_irq_flags__irq_3_w),
    .d2l__user_irq_flags__irq_3_we(d2l__user_irq_flags__irq_3_we),
    .d2l__user_irq_flags__irq_3_re(d2l__user_irq_flags__irq_3_re),
    .d2l__user_irq_flags__irq_4_w(d2l__user_irq_flags__irq_4_w),
    .d2l__user_irq_flags__irq_4_we(d2l__user_irq_flags__irq_4_we),
    .d2l__user_irq_flags__irq_4_re(d2l__user_irq_flags__irq_4_re),
    .d2l__user_irq_flags__irq_5_w(d2l__user_irq_flags__irq_5_w),
    .d2l__user_irq_flags__irq_5_we(d2l__user_irq_flags__irq_5_we),
    .d2l__user_irq_flags__irq_5_re(d2l__user_irq_flags__irq_5_re),
    .d2l__user_irq_flags__irq_6_w(d2l__user_irq_flags__irq_6_w),
    .d2l__user_irq_flags__irq_6_we(d2l__user_irq_flags__irq_6_we),
    .d2l__user_irq_flags__irq_6_re(d2l__user_irq_flags__irq_6_re),
    .d2l__user_irq_flags__irq_7_w(d2l__user_irq_flags__irq_7_w),
    .d2l__user_irq_flags__irq_7_we(d2l__user_irq_flags__irq_7_we),
    .d2l__user_irq_flags__irq_7_re(d2l__user_irq_flags__irq_7_re),
    .d2l__user_irq_flags__irq_8_w(d2l__user_irq_flags__irq_8_w),
    .d2l__user_irq_flags__irq_8_we(d2l__user_irq_flags__irq_8_we),
    .d2l__user_irq_flags__irq_8_re(d2l__user_irq_flags__irq_8_re),
    .d2l__user_irq_flags__irq_9_w(d2l__user_irq_flags__irq_9_w),
    .d2l__user_irq_flags__irq_9_we(d2l__user_irq_flags__irq_9_we),
    .d2l__user_irq_flags__irq_9_re(d2l__user_irq_flags__irq_9_re),
    .d2l__user_irq_flags__irq_10_w(d2l__user_irq_flags__irq_10_w),
    .d2l__user_irq_flags__irq_10_we(d2l__user_irq_flags__irq_10_we),
    .d2l__user_irq_flags__irq_10_re(d2l__user_irq_flags__irq_10_re),
    .d2l__user_irq_flags__irq_11_w(d2l__user_irq_flags__irq_11_w),
    .d2l__user_irq_flags__irq_11_we(d2l__user_irq_flags__irq_11_we),
    .d2l__user_irq_flags__irq_11_re(d2l__user_irq_flags__irq_11_re),
    .d2l__user_irq_flags__irq_12_w(d2l__user_irq_flags__irq_12_w),
    .d2l__user_irq_flags__irq_12_we(d2l__user_irq_flags__irq_12_we),
    .d2l__user_irq_flags__irq_12_re(d2l__user_irq_flags__irq_12_re),
    .d2l__user_irq_flags__irq_13_w(d2l__user_irq_flags__irq_13_w),
    .d2l__user_irq_flags__irq_13_we(d2l__user_irq_flags__irq_13_we),
    .d2l__user_irq_flags__irq_13_re(d2l__user_irq_flags__irq_13_re),
    .d2l__user_irq_flags__irq_14_w(d2l__user_irq_flags__irq_14_w),
    .d2l__user_irq_flags__irq_14_we(d2l__user_irq_flags__irq_14_we),
    .d2l__user_irq_flags__irq_14_re(d2l__user_irq_flags__irq_14_re),
    .d2l__user_irq_flags__irq_15_w(d2l__user_irq_flags__irq_15_w),
    .d2l__user_irq_flags__irq_15_we(d2l__user_irq_flags__irq_15_we),
    .d2l__user_irq_flags__irq_15_re(d2l__user_irq_flags__irq_15_re),
    .d2l__user_irq_en_flags__irq_en_0_w(d2l__user_irq_en_flags__irq_en_0_w),
    .d2l__user_irq_en_flags__irq_en_0_we(d2l__user_irq_en_flags__irq_en_0_we),
    .d2l__user_irq_en_flags__irq_en_0_re(d2l__user_irq_en_flags__irq_en_0_re),
    .d2l__user_irq_en_flags__irq_en_1_w(d2l__user_irq_en_flags__irq_en_1_w),
    .d2l__user_irq_en_flags__irq_en_1_we(d2l__user_irq_en_flags__irq_en_1_we),
    .d2l__user_irq_en_flags__irq_en_1_re(d2l__user_irq_en_flags__irq_en_1_re),
    .d2l__user_irq_en_flags__irq_en_2_w(d2l__user_irq_en_flags__irq_en_2_w),
    .d2l__user_irq_en_flags__irq_en_2_we(d2l__user_irq_en_flags__irq_en_2_we),
    .d2l__user_irq_en_flags__irq_en_2_re(d2l__user_irq_en_flags__irq_en_2_re),
    .d2l__user_irq_en_flags__irq_en_3_w(d2l__user_irq_en_flags__irq_en_3_w),
    .d2l__user_irq_en_flags__irq_en_3_we(d2l__user_irq_en_flags__irq_en_3_we),
    .d2l__user_irq_en_flags__irq_en_3_re(d2l__user_irq_en_flags__irq_en_3_re),
    .d2l__user_irq_en_flags__irq_en_4_w(d2l__user_irq_en_flags__irq_en_4_w),
    .d2l__user_irq_en_flags__irq_en_4_we(d2l__user_irq_en_flags__irq_en_4_we),
    .d2l__user_irq_en_flags__irq_en_4_re(d2l__user_irq_en_flags__irq_en_4_re),
    .d2l__user_irq_en_flags__irq_en_5_w(d2l__user_irq_en_flags__irq_en_5_w),
    .d2l__user_irq_en_flags__irq_en_5_we(d2l__user_irq_en_flags__irq_en_5_we),
    .d2l__user_irq_en_flags__irq_en_5_re(d2l__user_irq_en_flags__irq_en_5_re),
    .d2l__user_irq_en_flags__irq_en_6_w(d2l__user_irq_en_flags__irq_en_6_w),
    .d2l__user_irq_en_flags__irq_en_6_we(d2l__user_irq_en_flags__irq_en_6_we),
    .d2l__user_irq_en_flags__irq_en_6_re(d2l__user_irq_en_flags__irq_en_6_re),
    .d2l__user_irq_en_flags__irq_en_7_w(d2l__user_irq_en_flags__irq_en_7_w),
    .d2l__user_irq_en_flags__irq_en_7_we(d2l__user_irq_en_flags__irq_en_7_we),
    .d2l__user_irq_en_flags__irq_en_7_re(d2l__user_irq_en_flags__irq_en_7_re),
    .d2l__user_irq_en_flags__irq_en_8_w(d2l__user_irq_en_flags__irq_en_8_w),
    .d2l__user_irq_en_flags__irq_en_8_we(d2l__user_irq_en_flags__irq_en_8_we),
    .d2l__user_irq_en_flags__irq_en_8_re(d2l__user_irq_en_flags__irq_en_8_re),
    .d2l__user_irq_en_flags__irq_en_9_w(d2l__user_irq_en_flags__irq_en_9_w),
    .d2l__user_irq_en_flags__irq_en_9_we(d2l__user_irq_en_flags__irq_en_9_we),
    .d2l__user_irq_en_flags__irq_en_9_re(d2l__user_irq_en_flags__irq_en_9_re),
    .d2l__user_irq_en_flags__irq_en_10_w(d2l__user_irq_en_flags__irq_en_10_w),
    .d2l__user_irq_en_flags__irq_en_10_we(d2l__user_irq_en_flags__irq_en_10_we),
    .d2l__user_irq_en_flags__irq_en_10_re(d2l__user_irq_en_flags__irq_en_10_re),
    .d2l__user_irq_en_flags__irq_en_11_w(d2l__user_irq_en_flags__irq_en_11_w),
    .d2l__user_irq_en_flags__irq_en_11_we(d2l__user_irq_en_flags__irq_en_11_we),
    .d2l__user_irq_en_flags__irq_en_11_re(d2l__user_irq_en_flags__irq_en_11_re),
    .d2l__user_irq_en_flags__irq_en_12_w(d2l__user_irq_en_flags__irq_en_12_w),
    .d2l__user_irq_en_flags__irq_en_12_we(d2l__user_irq_en_flags__irq_en_12_we),
    .d2l__user_irq_en_flags__irq_en_12_re(d2l__user_irq_en_flags__irq_en_12_re),
    .d2l__user_irq_en_flags__irq_en_13_w(d2l__user_irq_en_flags__irq_en_13_w),
    .d2l__user_irq_en_flags__irq_en_13_we(d2l__user_irq_en_flags__irq_en_13_we),
    .d2l__user_irq_en_flags__irq_en_13_re(d2l__user_irq_en_flags__irq_en_13_re),
    .d2l__user_irq_en_flags__irq_en_14_w(d2l__user_irq_en_flags__irq_en_14_w),
    .d2l__user_irq_en_flags__irq_en_14_we(d2l__user_irq_en_flags__irq_en_14_we),
    .d2l__user_irq_en_flags__irq_en_14_re(d2l__user_irq_en_flags__irq_en_14_re),
    .d2l__user_irq_en_flags__irq_en_15_w(d2l__user_irq_en_flags__irq_en_15_w),
    .d2l__user_irq_en_flags__irq_en_15_we(d2l__user_irq_en_flags__irq_en_15_we),
    .d2l__user_irq_en_flags__irq_en_15_re(d2l__user_irq_en_flags__irq_en_15_re),
    .d2l__user_cfg_regs__user_cfg_0_w(d2l__user_cfg_regs__user_cfg_0_w),
    .d2l__user_cfg_regs__user_cfg_0_we(d2l__user_cfg_regs__user_cfg_0_we),
    .d2l__user_cfg_regs__user_cfg_0_re(d2l__user_cfg_regs__user_cfg_0_re),
    .d2l__user_cfg_regs__user_cfg_1_w(d2l__user_cfg_regs__user_cfg_1_w),
    .d2l__user_cfg_regs__user_cfg_1_we(d2l__user_cfg_regs__user_cfg_1_we),
    .d2l__user_cfg_regs__user_cfg_1_re(d2l__user_cfg_regs__user_cfg_1_re),
    .d2l__user_cfg_regs__user_cfg_2_w(d2l__user_cfg_regs__user_cfg_2_w),
    .d2l__user_cfg_regs__user_cfg_2_we(d2l__user_cfg_regs__user_cfg_2_we),
    .d2l__user_cfg_regs__user_cfg_2_re(d2l__user_cfg_regs__user_cfg_2_re),
    .d2l__user_cfg_regs__user_cfg_3_w(d2l__user_cfg_regs__user_cfg_3_w),
    .d2l__user_cfg_regs__user_cfg_3_we(d2l__user_cfg_regs__user_cfg_3_we),
    .d2l__user_cfg_regs__user_cfg_3_re(d2l__user_cfg_regs__user_cfg_3_re),
    .d2l__user_stat_regs__user_stat_0_w(d2l__user_stat_regs__user_stat_0_w),
    .d2l__user_stat_regs__user_stat_0_we(d2l__user_stat_regs__user_stat_0_we),
    .d2l__user_stat_regs__user_stat_0_re(d2l__user_stat_regs__user_stat_0_re),
    .d2l__user_stat_regs__user_stat_1_w(d2l__user_stat_regs__user_stat_1_w),
    .d2l__user_stat_regs__user_stat_1_we(d2l__user_stat_regs__user_stat_1_we),
    .d2l__user_stat_regs__user_stat_1_re(d2l__user_stat_regs__user_stat_1_re),
    .d2l__user_stat_regs__user_stat_2_w(d2l__user_stat_regs__user_stat_2_w),
    .d2l__user_stat_regs__user_stat_2_we(d2l__user_stat_regs__user_stat_2_we),
    .d2l__user_stat_regs__user_stat_2_re(d2l__user_stat_regs__user_stat_2_re),
    .d2l__user_stat_regs__user_stat_3_w(d2l__user_stat_regs__user_stat_3_w),
    .d2l__user_stat_regs__user_stat_3_we(d2l__user_stat_regs__user_stat_3_we),
    .d2l__user_stat_regs__user_stat_3_re(d2l__user_stat_regs__user_stat_3_re),
    .d2l__user_stat_regs__user_stat_4_w(d2l__user_stat_regs__user_stat_4_w),
    .d2l__user_stat_regs__user_stat_4_we(d2l__user_stat_regs__user_stat_4_we),
    .d2l__user_stat_regs__user_stat_4_re(d2l__user_stat_regs__user_stat_4_re),
    .d2l__user_stat_regs__user_stat_5_w(d2l__user_stat_regs__user_stat_5_w),
    .d2l__user_stat_regs__user_stat_5_we(d2l__user_stat_regs__user_stat_5_we),
    .d2l__user_stat_regs__user_stat_5_re(d2l__user_stat_regs__user_stat_5_re) );
    
  regfile_addr_map_jrdl_logic pio_logic (
    .clk(clk),
    .sig_reset_n(sig_reset_n),
    .d2l__control_w(d2l__control_w),
    .d2l__control_we(d2l__control_we),
    .d2l__control_re(d2l__control_re),
    .d2l__status_w(d2l__status_w),
    .d2l__status_we(d2l__status_we),
    .d2l__status_re(d2l__status_re),
    .d2l__user_irq_status_w(d2l__user_irq_status_w),
    .d2l__user_irq_status_we(d2l__user_irq_status_we),
    .d2l__user_irq_status_re(d2l__user_irq_status_re),
    .d2l__user_irq_enable_w(d2l__user_irq_enable_w),
    .d2l__user_irq_enable_we(d2l__user_irq_enable_we),
    .d2l__user_irq_enable_re(d2l__user_irq_enable_re),
    .d2l__user_irq_flags__irq_0_w(d2l__user_irq_flags__irq_0_w),
    .d2l__user_irq_flags__irq_0_we(d2l__user_irq_flags__irq_0_we),
    .d2l__user_irq_flags__irq_0_re(d2l__user_irq_flags__irq_0_re),
    .d2l__user_irq_flags__irq_1_w(d2l__user_irq_flags__irq_1_w),
    .d2l__user_irq_flags__irq_1_we(d2l__user_irq_flags__irq_1_we),
    .d2l__user_irq_flags__irq_1_re(d2l__user_irq_flags__irq_1_re),
    .d2l__user_irq_flags__irq_2_w(d2l__user_irq_flags__irq_2_w),
    .d2l__user_irq_flags__irq_2_we(d2l__user_irq_flags__irq_2_we),
    .d2l__user_irq_flags__irq_2_re(d2l__user_irq_flags__irq_2_re),
    .d2l__user_irq_flags__irq_3_w(d2l__user_irq_flags__irq_3_w),
    .d2l__user_irq_flags__irq_3_we(d2l__user_irq_flags__irq_3_we),
    .d2l__user_irq_flags__irq_3_re(d2l__user_irq_flags__irq_3_re),
    .d2l__user_irq_flags__irq_4_w(d2l__user_irq_flags__irq_4_w),
    .d2l__user_irq_flags__irq_4_we(d2l__user_irq_flags__irq_4_we),
    .d2l__user_irq_flags__irq_4_re(d2l__user_irq_flags__irq_4_re),
    .d2l__user_irq_flags__irq_5_w(d2l__user_irq_flags__irq_5_w),
    .d2l__user_irq_flags__irq_5_we(d2l__user_irq_flags__irq_5_we),
    .d2l__user_irq_flags__irq_5_re(d2l__user_irq_flags__irq_5_re),
    .d2l__user_irq_flags__irq_6_w(d2l__user_irq_flags__irq_6_w),
    .d2l__user_irq_flags__irq_6_we(d2l__user_irq_flags__irq_6_we),
    .d2l__user_irq_flags__irq_6_re(d2l__user_irq_flags__irq_6_re),
    .d2l__user_irq_flags__irq_7_w(d2l__user_irq_flags__irq_7_w),
    .d2l__user_irq_flags__irq_7_we(d2l__user_irq_flags__irq_7_we),
    .d2l__user_irq_flags__irq_7_re(d2l__user_irq_flags__irq_7_re),
    .d2l__user_irq_flags__irq_8_w(d2l__user_irq_flags__irq_8_w),
    .d2l__user_irq_flags__irq_8_we(d2l__user_irq_flags__irq_8_we),
    .d2l__user_irq_flags__irq_8_re(d2l__user_irq_flags__irq_8_re),
    .d2l__user_irq_flags__irq_9_w(d2l__user_irq_flags__irq_9_w),
    .d2l__user_irq_flags__irq_9_we(d2l__user_irq_flags__irq_9_we),
    .d2l__user_irq_flags__irq_9_re(d2l__user_irq_flags__irq_9_re),
    .d2l__user_irq_flags__irq_10_w(d2l__user_irq_flags__irq_10_w),
    .d2l__user_irq_flags__irq_10_we(d2l__user_irq_flags__irq_10_we),
    .d2l__user_irq_flags__irq_10_re(d2l__user_irq_flags__irq_10_re),
    .d2l__user_irq_flags__irq_11_w(d2l__user_irq_flags__irq_11_w),
    .d2l__user_irq_flags__irq_11_we(d2l__user_irq_flags__irq_11_we),
    .d2l__user_irq_flags__irq_11_re(d2l__user_irq_flags__irq_11_re),
    .d2l__user_irq_flags__irq_12_w(d2l__user_irq_flags__irq_12_w),
    .d2l__user_irq_flags__irq_12_we(d2l__user_irq_flags__irq_12_we),
    .d2l__user_irq_flags__irq_12_re(d2l__user_irq_flags__irq_12_re),
    .d2l__user_irq_flags__irq_13_w(d2l__user_irq_flags__irq_13_w),
    .d2l__user_irq_flags__irq_13_we(d2l__user_irq_flags__irq_13_we),
    .d2l__user_irq_flags__irq_13_re(d2l__user_irq_flags__irq_13_re),
    .d2l__user_irq_flags__irq_14_w(d2l__user_irq_flags__irq_14_w),
    .d2l__user_irq_flags__irq_14_we(d2l__user_irq_flags__irq_14_we),
    .d2l__user_irq_flags__irq_14_re(d2l__user_irq_flags__irq_14_re),
    .d2l__user_irq_flags__irq_15_w(d2l__user_irq_flags__irq_15_w),
    .d2l__user_irq_flags__irq_15_we(d2l__user_irq_flags__irq_15_we),
    .d2l__user_irq_flags__irq_15_re(d2l__user_irq_flags__irq_15_re),
    .d2l__user_irq_en_flags__irq_en_0_w(d2l__user_irq_en_flags__irq_en_0_w),
    .d2l__user_irq_en_flags__irq_en_0_we(d2l__user_irq_en_flags__irq_en_0_we),
    .d2l__user_irq_en_flags__irq_en_0_re(d2l__user_irq_en_flags__irq_en_0_re),
    .d2l__user_irq_en_flags__irq_en_1_w(d2l__user_irq_en_flags__irq_en_1_w),
    .d2l__user_irq_en_flags__irq_en_1_we(d2l__user_irq_en_flags__irq_en_1_we),
    .d2l__user_irq_en_flags__irq_en_1_re(d2l__user_irq_en_flags__irq_en_1_re),
    .d2l__user_irq_en_flags__irq_en_2_w(d2l__user_irq_en_flags__irq_en_2_w),
    .d2l__user_irq_en_flags__irq_en_2_we(d2l__user_irq_en_flags__irq_en_2_we),
    .d2l__user_irq_en_flags__irq_en_2_re(d2l__user_irq_en_flags__irq_en_2_re),
    .d2l__user_irq_en_flags__irq_en_3_w(d2l__user_irq_en_flags__irq_en_3_w),
    .d2l__user_irq_en_flags__irq_en_3_we(d2l__user_irq_en_flags__irq_en_3_we),
    .d2l__user_irq_en_flags__irq_en_3_re(d2l__user_irq_en_flags__irq_en_3_re),
    .d2l__user_irq_en_flags__irq_en_4_w(d2l__user_irq_en_flags__irq_en_4_w),
    .d2l__user_irq_en_flags__irq_en_4_we(d2l__user_irq_en_flags__irq_en_4_we),
    .d2l__user_irq_en_flags__irq_en_4_re(d2l__user_irq_en_flags__irq_en_4_re),
    .d2l__user_irq_en_flags__irq_en_5_w(d2l__user_irq_en_flags__irq_en_5_w),
    .d2l__user_irq_en_flags__irq_en_5_we(d2l__user_irq_en_flags__irq_en_5_we),
    .d2l__user_irq_en_flags__irq_en_5_re(d2l__user_irq_en_flags__irq_en_5_re),
    .d2l__user_irq_en_flags__irq_en_6_w(d2l__user_irq_en_flags__irq_en_6_w),
    .d2l__user_irq_en_flags__irq_en_6_we(d2l__user_irq_en_flags__irq_en_6_we),
    .d2l__user_irq_en_flags__irq_en_6_re(d2l__user_irq_en_flags__irq_en_6_re),
    .d2l__user_irq_en_flags__irq_en_7_w(d2l__user_irq_en_flags__irq_en_7_w),
    .d2l__user_irq_en_flags__irq_en_7_we(d2l__user_irq_en_flags__irq_en_7_we),
    .d2l__user_irq_en_flags__irq_en_7_re(d2l__user_irq_en_flags__irq_en_7_re),
    .d2l__user_irq_en_flags__irq_en_8_w(d2l__user_irq_en_flags__irq_en_8_w),
    .d2l__user_irq_en_flags__irq_en_8_we(d2l__user_irq_en_flags__irq_en_8_we),
    .d2l__user_irq_en_flags__irq_en_8_re(d2l__user_irq_en_flags__irq_en_8_re),
    .d2l__user_irq_en_flags__irq_en_9_w(d2l__user_irq_en_flags__irq_en_9_w),
    .d2l__user_irq_en_flags__irq_en_9_we(d2l__user_irq_en_flags__irq_en_9_we),
    .d2l__user_irq_en_flags__irq_en_9_re(d2l__user_irq_en_flags__irq_en_9_re),
    .d2l__user_irq_en_flags__irq_en_10_w(d2l__user_irq_en_flags__irq_en_10_w),
    .d2l__user_irq_en_flags__irq_en_10_we(d2l__user_irq_en_flags__irq_en_10_we),
    .d2l__user_irq_en_flags__irq_en_10_re(d2l__user_irq_en_flags__irq_en_10_re),
    .d2l__user_irq_en_flags__irq_en_11_w(d2l__user_irq_en_flags__irq_en_11_w),
    .d2l__user_irq_en_flags__irq_en_11_we(d2l__user_irq_en_flags__irq_en_11_we),
    .d2l__user_irq_en_flags__irq_en_11_re(d2l__user_irq_en_flags__irq_en_11_re),
    .d2l__user_irq_en_flags__irq_en_12_w(d2l__user_irq_en_flags__irq_en_12_w),
    .d2l__user_irq_en_flags__irq_en_12_we(d2l__user_irq_en_flags__irq_en_12_we),
    .d2l__user_irq_en_flags__irq_en_12_re(d2l__user_irq_en_flags__irq_en_12_re),
    .d2l__user_irq_en_flags__irq_en_13_w(d2l__user_irq_en_flags__irq_en_13_w),
    .d2l__user_irq_en_flags__irq_en_13_we(d2l__user_irq_en_flags__irq_en_13_we),
    .d2l__user_irq_en_flags__irq_en_13_re(d2l__user_irq_en_flags__irq_en_13_re),
    .d2l__user_irq_en_flags__irq_en_14_w(d2l__user_irq_en_flags__irq_en_14_w),
    .d2l__user_irq_en_flags__irq_en_14_we(d2l__user_irq_en_flags__irq_en_14_we),
    .d2l__user_irq_en_flags__irq_en_14_re(d2l__user_irq_en_flags__irq_en_14_re),
    .d2l__user_irq_en_flags__irq_en_15_w(d2l__user_irq_en_flags__irq_en_15_w),
    .d2l__user_irq_en_flags__irq_en_15_we(d2l__user_irq_en_flags__irq_en_15_we),
    .d2l__user_irq_en_flags__irq_en_15_re(d2l__user_irq_en_flags__irq_en_15_re),
    .d2l__user_cfg_regs__user_cfg_0_w(d2l__user_cfg_regs__user_cfg_0_w),
    .d2l__user_cfg_regs__user_cfg_0_we(d2l__user_cfg_regs__user_cfg_0_we),
    .d2l__user_cfg_regs__user_cfg_0_re(d2l__user_cfg_regs__user_cfg_0_re),
    .d2l__user_cfg_regs__user_cfg_1_w(d2l__user_cfg_regs__user_cfg_1_w),
    .d2l__user_cfg_regs__user_cfg_1_we(d2l__user_cfg_regs__user_cfg_1_we),
    .d2l__user_cfg_regs__user_cfg_1_re(d2l__user_cfg_regs__user_cfg_1_re),
    .d2l__user_cfg_regs__user_cfg_2_w(d2l__user_cfg_regs__user_cfg_2_w),
    .d2l__user_cfg_regs__user_cfg_2_we(d2l__user_cfg_regs__user_cfg_2_we),
    .d2l__user_cfg_regs__user_cfg_2_re(d2l__user_cfg_regs__user_cfg_2_re),
    .d2l__user_cfg_regs__user_cfg_3_w(d2l__user_cfg_regs__user_cfg_3_w),
    .d2l__user_cfg_regs__user_cfg_3_we(d2l__user_cfg_regs__user_cfg_3_we),
    .d2l__user_cfg_regs__user_cfg_3_re(d2l__user_cfg_regs__user_cfg_3_re),
    .d2l__user_stat_regs__user_stat_0_w(d2l__user_stat_regs__user_stat_0_w),
    .d2l__user_stat_regs__user_stat_0_we(d2l__user_stat_regs__user_stat_0_we),
    .d2l__user_stat_regs__user_stat_0_re(d2l__user_stat_regs__user_stat_0_re),
    .d2l__user_stat_regs__user_stat_1_w(d2l__user_stat_regs__user_stat_1_w),
    .d2l__user_stat_regs__user_stat_1_we(d2l__user_stat_regs__user_stat_1_we),
    .d2l__user_stat_regs__user_stat_1_re(d2l__user_stat_regs__user_stat_1_re),
    .d2l__user_stat_regs__user_stat_2_w(d2l__user_stat_regs__user_stat_2_w),
    .d2l__user_stat_regs__user_stat_2_we(d2l__user_stat_regs__user_stat_2_we),
    .d2l__user_stat_regs__user_stat_2_re(d2l__user_stat_regs__user_stat_2_re),
    .d2l__user_stat_regs__user_stat_3_w(d2l__user_stat_regs__user_stat_3_w),
    .d2l__user_stat_regs__user_stat_3_we(d2l__user_stat_regs__user_stat_3_we),
    .d2l__user_stat_regs__user_stat_3_re(d2l__user_stat_regs__user_stat_3_re),
    .d2l__user_stat_regs__user_stat_4_w(d2l__user_stat_regs__user_stat_4_w),
    .d2l__user_stat_regs__user_stat_4_we(d2l__user_stat_regs__user_stat_4_we),
    .d2l__user_stat_regs__user_stat_4_re(d2l__user_stat_regs__user_stat_4_re),
    .d2l__user_stat_regs__user_stat_5_w(d2l__user_stat_regs__user_stat_5_w),
    .d2l__user_stat_regs__user_stat_5_we(d2l__user_stat_regs__user_stat_5_we),
    .d2l__user_stat_regs__user_stat_5_re(d2l__user_stat_regs__user_stat_5_re),
    .h2l__user_irq_flags__irq_0__user_irq_0_intr(h2l__user_irq_flags__irq_0__user_irq_0_intr),
    .h2l__user_irq_flags__irq_0__user_irq_1_intr(h2l__user_irq_flags__irq_0__user_irq_1_intr),
    .h2l__user_irq_flags__irq_0__user_irq_2_intr(h2l__user_irq_flags__irq_0__user_irq_2_intr),
    .h2l__user_irq_flags__irq_0__user_irq_3_intr(h2l__user_irq_flags__irq_0__user_irq_3_intr),
    .h2l__user_irq_flags__irq_0__user_irq_4_intr(h2l__user_irq_flags__irq_0__user_irq_4_intr),
    .h2l__user_irq_flags__irq_0__user_irq_5_intr(h2l__user_irq_flags__irq_0__user_irq_5_intr),
    .h2l__user_irq_flags__irq_0__user_irq_6_intr(h2l__user_irq_flags__irq_0__user_irq_6_intr),
    .h2l__user_irq_flags__irq_0__user_irq_7_intr(h2l__user_irq_flags__irq_0__user_irq_7_intr),
    .h2l__user_irq_flags__irq_1__user_irq_0_intr(h2l__user_irq_flags__irq_1__user_irq_0_intr),
    .h2l__user_irq_flags__irq_1__user_irq_1_intr(h2l__user_irq_flags__irq_1__user_irq_1_intr),
    .h2l__user_irq_flags__irq_1__user_irq_2_intr(h2l__user_irq_flags__irq_1__user_irq_2_intr),
    .h2l__user_irq_flags__irq_1__user_irq_3_intr(h2l__user_irq_flags__irq_1__user_irq_3_intr),
    .h2l__user_irq_flags__irq_1__user_irq_4_intr(h2l__user_irq_flags__irq_1__user_irq_4_intr),
    .h2l__user_irq_flags__irq_1__user_irq_5_intr(h2l__user_irq_flags__irq_1__user_irq_5_intr),
    .h2l__user_irq_flags__irq_1__user_irq_6_intr(h2l__user_irq_flags__irq_1__user_irq_6_intr),
    .h2l__user_irq_flags__irq_1__user_irq_7_intr(h2l__user_irq_flags__irq_1__user_irq_7_intr),
    .h2l__user_irq_flags__irq_2__user_irq_0_intr(h2l__user_irq_flags__irq_2__user_irq_0_intr),
    .h2l__user_irq_flags__irq_2__user_irq_1_intr(h2l__user_irq_flags__irq_2__user_irq_1_intr),
    .h2l__user_irq_flags__irq_2__user_irq_2_intr(h2l__user_irq_flags__irq_2__user_irq_2_intr),
    .h2l__user_irq_flags__irq_2__user_irq_3_intr(h2l__user_irq_flags__irq_2__user_irq_3_intr),
    .h2l__user_irq_flags__irq_2__user_irq_4_intr(h2l__user_irq_flags__irq_2__user_irq_4_intr),
    .h2l__user_irq_flags__irq_2__user_irq_5_intr(h2l__user_irq_flags__irq_2__user_irq_5_intr),
    .h2l__user_irq_flags__irq_2__user_irq_6_intr(h2l__user_irq_flags__irq_2__user_irq_6_intr),
    .h2l__user_irq_flags__irq_2__user_irq_7_intr(h2l__user_irq_flags__irq_2__user_irq_7_intr),
    .h2l__user_irq_flags__irq_3__user_irq_0_intr(h2l__user_irq_flags__irq_3__user_irq_0_intr),
    .h2l__user_irq_flags__irq_3__user_irq_1_intr(h2l__user_irq_flags__irq_3__user_irq_1_intr),
    .h2l__user_irq_flags__irq_3__user_irq_2_intr(h2l__user_irq_flags__irq_3__user_irq_2_intr),
    .h2l__user_irq_flags__irq_3__user_irq_3_intr(h2l__user_irq_flags__irq_3__user_irq_3_intr),
    .h2l__user_irq_flags__irq_3__user_irq_4_intr(h2l__user_irq_flags__irq_3__user_irq_4_intr),
    .h2l__user_irq_flags__irq_3__user_irq_5_intr(h2l__user_irq_flags__irq_3__user_irq_5_intr),
    .h2l__user_irq_flags__irq_3__user_irq_6_intr(h2l__user_irq_flags__irq_3__user_irq_6_intr),
    .h2l__user_irq_flags__irq_3__user_irq_7_intr(h2l__user_irq_flags__irq_3__user_irq_7_intr),
    .h2l__user_irq_flags__irq_4__user_irq_0_intr(h2l__user_irq_flags__irq_4__user_irq_0_intr),
    .h2l__user_irq_flags__irq_4__user_irq_1_intr(h2l__user_irq_flags__irq_4__user_irq_1_intr),
    .h2l__user_irq_flags__irq_4__user_irq_2_intr(h2l__user_irq_flags__irq_4__user_irq_2_intr),
    .h2l__user_irq_flags__irq_4__user_irq_3_intr(h2l__user_irq_flags__irq_4__user_irq_3_intr),
    .h2l__user_irq_flags__irq_4__user_irq_4_intr(h2l__user_irq_flags__irq_4__user_irq_4_intr),
    .h2l__user_irq_flags__irq_4__user_irq_5_intr(h2l__user_irq_flags__irq_4__user_irq_5_intr),
    .h2l__user_irq_flags__irq_4__user_irq_6_intr(h2l__user_irq_flags__irq_4__user_irq_6_intr),
    .h2l__user_irq_flags__irq_4__user_irq_7_intr(h2l__user_irq_flags__irq_4__user_irq_7_intr),
    .h2l__user_irq_flags__irq_5__user_irq_0_intr(h2l__user_irq_flags__irq_5__user_irq_0_intr),
    .h2l__user_irq_flags__irq_5__user_irq_1_intr(h2l__user_irq_flags__irq_5__user_irq_1_intr),
    .h2l__user_irq_flags__irq_5__user_irq_2_intr(h2l__user_irq_flags__irq_5__user_irq_2_intr),
    .h2l__user_irq_flags__irq_5__user_irq_3_intr(h2l__user_irq_flags__irq_5__user_irq_3_intr),
    .h2l__user_irq_flags__irq_5__user_irq_4_intr(h2l__user_irq_flags__irq_5__user_irq_4_intr),
    .h2l__user_irq_flags__irq_5__user_irq_5_intr(h2l__user_irq_flags__irq_5__user_irq_5_intr),
    .h2l__user_irq_flags__irq_5__user_irq_6_intr(h2l__user_irq_flags__irq_5__user_irq_6_intr),
    .h2l__user_irq_flags__irq_5__user_irq_7_intr(h2l__user_irq_flags__irq_5__user_irq_7_intr),
    .h2l__user_irq_flags__irq_6__user_irq_0_intr(h2l__user_irq_flags__irq_6__user_irq_0_intr),
    .h2l__user_irq_flags__irq_6__user_irq_1_intr(h2l__user_irq_flags__irq_6__user_irq_1_intr),
    .h2l__user_irq_flags__irq_6__user_irq_2_intr(h2l__user_irq_flags__irq_6__user_irq_2_intr),
    .h2l__user_irq_flags__irq_6__user_irq_3_intr(h2l__user_irq_flags__irq_6__user_irq_3_intr),
    .h2l__user_irq_flags__irq_6__user_irq_4_intr(h2l__user_irq_flags__irq_6__user_irq_4_intr),
    .h2l__user_irq_flags__irq_6__user_irq_5_intr(h2l__user_irq_flags__irq_6__user_irq_5_intr),
    .h2l__user_irq_flags__irq_6__user_irq_6_intr(h2l__user_irq_flags__irq_6__user_irq_6_intr),
    .h2l__user_irq_flags__irq_6__user_irq_7_intr(h2l__user_irq_flags__irq_6__user_irq_7_intr),
    .h2l__user_irq_flags__irq_7__user_irq_0_intr(h2l__user_irq_flags__irq_7__user_irq_0_intr),
    .h2l__user_irq_flags__irq_7__user_irq_1_intr(h2l__user_irq_flags__irq_7__user_irq_1_intr),
    .h2l__user_irq_flags__irq_7__user_irq_2_intr(h2l__user_irq_flags__irq_7__user_irq_2_intr),
    .h2l__user_irq_flags__irq_7__user_irq_3_intr(h2l__user_irq_flags__irq_7__user_irq_3_intr),
    .h2l__user_irq_flags__irq_7__user_irq_4_intr(h2l__user_irq_flags__irq_7__user_irq_4_intr),
    .h2l__user_irq_flags__irq_7__user_irq_5_intr(h2l__user_irq_flags__irq_7__user_irq_5_intr),
    .h2l__user_irq_flags__irq_7__user_irq_6_intr(h2l__user_irq_flags__irq_7__user_irq_6_intr),
    .h2l__user_irq_flags__irq_7__user_irq_7_intr(h2l__user_irq_flags__irq_7__user_irq_7_intr),
    .h2l__user_irq_flags__irq_8__user_irq_0_intr(h2l__user_irq_flags__irq_8__user_irq_0_intr),
    .h2l__user_irq_flags__irq_8__user_irq_1_intr(h2l__user_irq_flags__irq_8__user_irq_1_intr),
    .h2l__user_irq_flags__irq_8__user_irq_2_intr(h2l__user_irq_flags__irq_8__user_irq_2_intr),
    .h2l__user_irq_flags__irq_8__user_irq_3_intr(h2l__user_irq_flags__irq_8__user_irq_3_intr),
    .h2l__user_irq_flags__irq_8__user_irq_4_intr(h2l__user_irq_flags__irq_8__user_irq_4_intr),
    .h2l__user_irq_flags__irq_8__user_irq_5_intr(h2l__user_irq_flags__irq_8__user_irq_5_intr),
    .h2l__user_irq_flags__irq_8__user_irq_6_intr(h2l__user_irq_flags__irq_8__user_irq_6_intr),
    .h2l__user_irq_flags__irq_8__user_irq_7_intr(h2l__user_irq_flags__irq_8__user_irq_7_intr),
    .h2l__user_irq_flags__irq_9__user_irq_0_intr(h2l__user_irq_flags__irq_9__user_irq_0_intr),
    .h2l__user_irq_flags__irq_9__user_irq_1_intr(h2l__user_irq_flags__irq_9__user_irq_1_intr),
    .h2l__user_irq_flags__irq_9__user_irq_2_intr(h2l__user_irq_flags__irq_9__user_irq_2_intr),
    .h2l__user_irq_flags__irq_9__user_irq_3_intr(h2l__user_irq_flags__irq_9__user_irq_3_intr),
    .h2l__user_irq_flags__irq_9__user_irq_4_intr(h2l__user_irq_flags__irq_9__user_irq_4_intr),
    .h2l__user_irq_flags__irq_9__user_irq_5_intr(h2l__user_irq_flags__irq_9__user_irq_5_intr),
    .h2l__user_irq_flags__irq_9__user_irq_6_intr(h2l__user_irq_flags__irq_9__user_irq_6_intr),
    .h2l__user_irq_flags__irq_9__user_irq_7_intr(h2l__user_irq_flags__irq_9__user_irq_7_intr),
    .h2l__user_irq_flags__irq_10__user_irq_0_intr(h2l__user_irq_flags__irq_10__user_irq_0_intr),
    .h2l__user_irq_flags__irq_10__user_irq_1_intr(h2l__user_irq_flags__irq_10__user_irq_1_intr),
    .h2l__user_irq_flags__irq_10__user_irq_2_intr(h2l__user_irq_flags__irq_10__user_irq_2_intr),
    .h2l__user_irq_flags__irq_10__user_irq_3_intr(h2l__user_irq_flags__irq_10__user_irq_3_intr),
    .h2l__user_irq_flags__irq_10__user_irq_4_intr(h2l__user_irq_flags__irq_10__user_irq_4_intr),
    .h2l__user_irq_flags__irq_10__user_irq_5_intr(h2l__user_irq_flags__irq_10__user_irq_5_intr),
    .h2l__user_irq_flags__irq_10__user_irq_6_intr(h2l__user_irq_flags__irq_10__user_irq_6_intr),
    .h2l__user_irq_flags__irq_10__user_irq_7_intr(h2l__user_irq_flags__irq_10__user_irq_7_intr),
    .h2l__user_irq_flags__irq_11__user_irq_0_intr(h2l__user_irq_flags__irq_11__user_irq_0_intr),
    .h2l__user_irq_flags__irq_11__user_irq_1_intr(h2l__user_irq_flags__irq_11__user_irq_1_intr),
    .h2l__user_irq_flags__irq_11__user_irq_2_intr(h2l__user_irq_flags__irq_11__user_irq_2_intr),
    .h2l__user_irq_flags__irq_11__user_irq_3_intr(h2l__user_irq_flags__irq_11__user_irq_3_intr),
    .h2l__user_irq_flags__irq_11__user_irq_4_intr(h2l__user_irq_flags__irq_11__user_irq_4_intr),
    .h2l__user_irq_flags__irq_11__user_irq_5_intr(h2l__user_irq_flags__irq_11__user_irq_5_intr),
    .h2l__user_irq_flags__irq_11__user_irq_6_intr(h2l__user_irq_flags__irq_11__user_irq_6_intr),
    .h2l__user_irq_flags__irq_11__user_irq_7_intr(h2l__user_irq_flags__irq_11__user_irq_7_intr),
    .h2l__user_irq_flags__irq_12__user_irq_0_intr(h2l__user_irq_flags__irq_12__user_irq_0_intr),
    .h2l__user_irq_flags__irq_12__user_irq_1_intr(h2l__user_irq_flags__irq_12__user_irq_1_intr),
    .h2l__user_irq_flags__irq_12__user_irq_2_intr(h2l__user_irq_flags__irq_12__user_irq_2_intr),
    .h2l__user_irq_flags__irq_12__user_irq_3_intr(h2l__user_irq_flags__irq_12__user_irq_3_intr),
    .h2l__user_irq_flags__irq_12__user_irq_4_intr(h2l__user_irq_flags__irq_12__user_irq_4_intr),
    .h2l__user_irq_flags__irq_12__user_irq_5_intr(h2l__user_irq_flags__irq_12__user_irq_5_intr),
    .h2l__user_irq_flags__irq_12__user_irq_6_intr(h2l__user_irq_flags__irq_12__user_irq_6_intr),
    .h2l__user_irq_flags__irq_12__user_irq_7_intr(h2l__user_irq_flags__irq_12__user_irq_7_intr),
    .h2l__user_irq_flags__irq_13__user_irq_0_intr(h2l__user_irq_flags__irq_13__user_irq_0_intr),
    .h2l__user_irq_flags__irq_13__user_irq_1_intr(h2l__user_irq_flags__irq_13__user_irq_1_intr),
    .h2l__user_irq_flags__irq_13__user_irq_2_intr(h2l__user_irq_flags__irq_13__user_irq_2_intr),
    .h2l__user_irq_flags__irq_13__user_irq_3_intr(h2l__user_irq_flags__irq_13__user_irq_3_intr),
    .h2l__user_irq_flags__irq_13__user_irq_4_intr(h2l__user_irq_flags__irq_13__user_irq_4_intr),
    .h2l__user_irq_flags__irq_13__user_irq_5_intr(h2l__user_irq_flags__irq_13__user_irq_5_intr),
    .h2l__user_irq_flags__irq_13__user_irq_6_intr(h2l__user_irq_flags__irq_13__user_irq_6_intr),
    .h2l__user_irq_flags__irq_13__user_irq_7_intr(h2l__user_irq_flags__irq_13__user_irq_7_intr),
    .h2l__user_irq_flags__irq_14__user_irq_0_intr(h2l__user_irq_flags__irq_14__user_irq_0_intr),
    .h2l__user_irq_flags__irq_14__user_irq_1_intr(h2l__user_irq_flags__irq_14__user_irq_1_intr),
    .h2l__user_irq_flags__irq_14__user_irq_2_intr(h2l__user_irq_flags__irq_14__user_irq_2_intr),
    .h2l__user_irq_flags__irq_14__user_irq_3_intr(h2l__user_irq_flags__irq_14__user_irq_3_intr),
    .h2l__user_irq_flags__irq_14__user_irq_4_intr(h2l__user_irq_flags__irq_14__user_irq_4_intr),
    .h2l__user_irq_flags__irq_14__user_irq_5_intr(h2l__user_irq_flags__irq_14__user_irq_5_intr),
    .h2l__user_irq_flags__irq_14__user_irq_6_intr(h2l__user_irq_flags__irq_14__user_irq_6_intr),
    .h2l__user_irq_flags__irq_14__user_irq_7_intr(h2l__user_irq_flags__irq_14__user_irq_7_intr),
    .h2l__user_irq_flags__irq_15__user_irq_0_intr(h2l__user_irq_flags__irq_15__user_irq_0_intr),
    .h2l__user_irq_flags__irq_15__user_irq_1_intr(h2l__user_irq_flags__irq_15__user_irq_1_intr),
    .h2l__user_irq_flags__irq_15__user_irq_2_intr(h2l__user_irq_flags__irq_15__user_irq_2_intr),
    .h2l__user_irq_flags__irq_15__user_irq_3_intr(h2l__user_irq_flags__irq_15__user_irq_3_intr),
    .h2l__user_irq_flags__irq_15__user_irq_4_intr(h2l__user_irq_flags__irq_15__user_irq_4_intr),
    .h2l__user_irq_flags__irq_15__user_irq_5_intr(h2l__user_irq_flags__irq_15__user_irq_5_intr),
    .h2l__user_irq_flags__irq_15__user_irq_6_intr(h2l__user_irq_flags__irq_15__user_irq_6_intr),
    .h2l__user_irq_flags__irq_15__user_irq_7_intr(h2l__user_irq_flags__irq_15__user_irq_7_intr),
    .h2l__user_stat_regs__user_stat_0_user_stat_w(h2l__user_stat_regs__user_stat_0_user_stat_w),
    .h2l__user_stat_regs__user_stat_0_user_stat_we(h2l__user_stat_regs__user_stat_0_user_stat_we),
    .h2l__user_stat_regs__user_stat_1_user_stat_w(h2l__user_stat_regs__user_stat_1_user_stat_w),
    .h2l__user_stat_regs__user_stat_1_user_stat_we(h2l__user_stat_regs__user_stat_1_user_stat_we),
    .h2l__user_stat_regs__user_stat_2_user_stat_w(h2l__user_stat_regs__user_stat_2_user_stat_w),
    .h2l__user_stat_regs__user_stat_2_user_stat_we(h2l__user_stat_regs__user_stat_2_user_stat_we),
    .h2l__user_stat_regs__user_stat_3_user_stat_w(h2l__user_stat_regs__user_stat_3_user_stat_w),
    .h2l__user_stat_regs__user_stat_3_user_stat_we(h2l__user_stat_regs__user_stat_3_user_stat_we),
    .h2l__user_stat_regs__user_stat_4_user_stat_w(h2l__user_stat_regs__user_stat_4_user_stat_w),
    .h2l__user_stat_regs__user_stat_4_user_stat_we(h2l__user_stat_regs__user_stat_4_user_stat_we),
    .h2l__user_stat_regs__user_stat_5_user_stat_w(h2l__user_stat_regs__user_stat_5_user_stat_w),
    .h2l__user_stat_regs__user_stat_5_user_stat_we(h2l__user_stat_regs__user_stat_5_user_stat_we),
    .l2d__control_r(l2d__control_r),
    .l2d__status_r(l2d__status_r),
    .l2d__user_irq_status_r(l2d__user_irq_status_r),
    .l2d__user_irq_enable_r(l2d__user_irq_enable_r),
    .l2d__user_irq_flags__irq_0_r(l2d__user_irq_flags__irq_0_r),
    .l2d__user_irq_flags__irq_1_r(l2d__user_irq_flags__irq_1_r),
    .l2d__user_irq_flags__irq_2_r(l2d__user_irq_flags__irq_2_r),
    .l2d__user_irq_flags__irq_3_r(l2d__user_irq_flags__irq_3_r),
    .l2d__user_irq_flags__irq_4_r(l2d__user_irq_flags__irq_4_r),
    .l2d__user_irq_flags__irq_5_r(l2d__user_irq_flags__irq_5_r),
    .l2d__user_irq_flags__irq_6_r(l2d__user_irq_flags__irq_6_r),
    .l2d__user_irq_flags__irq_7_r(l2d__user_irq_flags__irq_7_r),
    .l2d__user_irq_flags__irq_8_r(l2d__user_irq_flags__irq_8_r),
    .l2d__user_irq_flags__irq_9_r(l2d__user_irq_flags__irq_9_r),
    .l2d__user_irq_flags__irq_10_r(l2d__user_irq_flags__irq_10_r),
    .l2d__user_irq_flags__irq_11_r(l2d__user_irq_flags__irq_11_r),
    .l2d__user_irq_flags__irq_12_r(l2d__user_irq_flags__irq_12_r),
    .l2d__user_irq_flags__irq_13_r(l2d__user_irq_flags__irq_13_r),
    .l2d__user_irq_flags__irq_14_r(l2d__user_irq_flags__irq_14_r),
    .l2d__user_irq_flags__irq_15_r(l2d__user_irq_flags__irq_15_r),
    .l2d__user_irq_en_flags__irq_en_0_r(l2d__user_irq_en_flags__irq_en_0_r),
    .l2d__user_irq_en_flags__irq_en_1_r(l2d__user_irq_en_flags__irq_en_1_r),
    .l2d__user_irq_en_flags__irq_en_2_r(l2d__user_irq_en_flags__irq_en_2_r),
    .l2d__user_irq_en_flags__irq_en_3_r(l2d__user_irq_en_flags__irq_en_3_r),
    .l2d__user_irq_en_flags__irq_en_4_r(l2d__user_irq_en_flags__irq_en_4_r),
    .l2d__user_irq_en_flags__irq_en_5_r(l2d__user_irq_en_flags__irq_en_5_r),
    .l2d__user_irq_en_flags__irq_en_6_r(l2d__user_irq_en_flags__irq_en_6_r),
    .l2d__user_irq_en_flags__irq_en_7_r(l2d__user_irq_en_flags__irq_en_7_r),
    .l2d__user_irq_en_flags__irq_en_8_r(l2d__user_irq_en_flags__irq_en_8_r),
    .l2d__user_irq_en_flags__irq_en_9_r(l2d__user_irq_en_flags__irq_en_9_r),
    .l2d__user_irq_en_flags__irq_en_10_r(l2d__user_irq_en_flags__irq_en_10_r),
    .l2d__user_irq_en_flags__irq_en_11_r(l2d__user_irq_en_flags__irq_en_11_r),
    .l2d__user_irq_en_flags__irq_en_12_r(l2d__user_irq_en_flags__irq_en_12_r),
    .l2d__user_irq_en_flags__irq_en_13_r(l2d__user_irq_en_flags__irq_en_13_r),
    .l2d__user_irq_en_flags__irq_en_14_r(l2d__user_irq_en_flags__irq_en_14_r),
    .l2d__user_irq_en_flags__irq_en_15_r(l2d__user_irq_en_flags__irq_en_15_r),
    .l2d__user_cfg_regs__user_cfg_0_r(l2d__user_cfg_regs__user_cfg_0_r),
    .l2d__user_cfg_regs__user_cfg_1_r(l2d__user_cfg_regs__user_cfg_1_r),
    .l2d__user_cfg_regs__user_cfg_2_r(l2d__user_cfg_regs__user_cfg_2_r),
    .l2d__user_cfg_regs__user_cfg_3_r(l2d__user_cfg_regs__user_cfg_3_r),
    .l2d__user_stat_regs__user_stat_0_r(l2d__user_stat_regs__user_stat_0_r),
    .l2d__user_stat_regs__user_stat_1_r(l2d__user_stat_regs__user_stat_1_r),
    .l2d__user_stat_regs__user_stat_2_r(l2d__user_stat_regs__user_stat_2_r),
    .l2d__user_stat_regs__user_stat_3_r(l2d__user_stat_regs__user_stat_3_r),
    .l2d__user_stat_regs__user_stat_4_r(l2d__user_stat_regs__user_stat_4_r),
    .l2d__user_stat_regs__user_stat_5_r(l2d__user_stat_regs__user_stat_5_r),
    .l2h__status_intr_o(l2h__status_intr_o),
    .l2h__user_irq_status_intr_o(l2h__user_irq_status_intr_o),
    .l2h__user_irq_flags__irq_0_intr_o(l2h__user_irq_flags__irq_0_intr_o),
    .l2h__user_irq_flags__irq_1_intr_o(l2h__user_irq_flags__irq_1_intr_o),
    .l2h__user_irq_flags__irq_2_intr_o(l2h__user_irq_flags__irq_2_intr_o),
    .l2h__user_irq_flags__irq_3_intr_o(l2h__user_irq_flags__irq_3_intr_o),
    .l2h__user_irq_flags__irq_4_intr_o(l2h__user_irq_flags__irq_4_intr_o),
    .l2h__user_irq_flags__irq_5_intr_o(l2h__user_irq_flags__irq_5_intr_o),
    .l2h__user_irq_flags__irq_6_intr_o(l2h__user_irq_flags__irq_6_intr_o),
    .l2h__user_irq_flags__irq_7_intr_o(l2h__user_irq_flags__irq_7_intr_o),
    .l2h__user_irq_flags__irq_8_intr_o(l2h__user_irq_flags__irq_8_intr_o),
    .l2h__user_irq_flags__irq_9_intr_o(l2h__user_irq_flags__irq_9_intr_o),
    .l2h__user_irq_flags__irq_10_intr_o(l2h__user_irq_flags__irq_10_intr_o),
    .l2h__user_irq_flags__irq_11_intr_o(l2h__user_irq_flags__irq_11_intr_o),
    .l2h__user_irq_flags__irq_12_intr_o(l2h__user_irq_flags__irq_12_intr_o),
    .l2h__user_irq_flags__irq_13_intr_o(l2h__user_irq_flags__irq_13_intr_o),
    .l2h__user_irq_flags__irq_14_intr_o(l2h__user_irq_flags__irq_14_intr_o),
    .l2h__user_irq_flags__irq_15_intr_o(l2h__user_irq_flags__irq_15_intr_o),
    .l2h__user_cfg_regs__user_cfg_0_user_cfg_r(l2h__user_cfg_regs__user_cfg_0_user_cfg_r),
    .l2h__user_cfg_regs__user_cfg_1_user_cfg_r(l2h__user_cfg_regs__user_cfg_1_user_cfg_r),
    .l2h__user_cfg_regs__user_cfg_2_user_cfg_r(l2h__user_cfg_regs__user_cfg_2_user_cfg_r),
    .l2h__user_cfg_regs__user_cfg_3_user_cfg_r(l2h__user_cfg_regs__user_cfg_3_user_cfg_r) );
    
endmodule

