//   Ordt 190617.01 autogenerated file 
//   Input: /home/shareef/git/cocotb-regfile/rdl/regfile.rdl.pp.final
//   Parms: /home/shareef/git/cocotb-regfile/rdl/rdl.params
//   Date: Fri Jun 28 12:46:33 BST 2019
//

//
//---------- module regfile_addr_map_jrdl_decode
//
module regfile_addr_map_jrdl_decode
(
  clk,
  sig_reset_n,
  h2d_pio_dec_address,
  h2d_pio_dec_write_data,
  h2d_pio_dec_trans_size,
  h2d_pio_dec_write,
  h2d_pio_dec_read,
  l2d__control_r,
  l2d__status_r,
  l2d__user_irq_status_r,
  l2d__user_irq_enable_r,
  l2d__user_irq_flags__irq_0_r,
  l2d__user_irq_flags__irq_1_r,
  l2d__user_irq_flags__irq_2_r,
  l2d__user_irq_flags__irq_3_r,
  l2d__user_irq_flags__irq_4_r,
  l2d__user_irq_flags__irq_5_r,
  l2d__user_irq_flags__irq_6_r,
  l2d__user_irq_flags__irq_7_r,
  l2d__user_irq_flags__irq_8_r,
  l2d__user_irq_flags__irq_9_r,
  l2d__user_irq_flags__irq_10_r,
  l2d__user_irq_flags__irq_11_r,
  l2d__user_irq_flags__irq_12_r,
  l2d__user_irq_flags__irq_13_r,
  l2d__user_irq_flags__irq_14_r,
  l2d__user_irq_flags__irq_15_r,
  l2d__user_irq_en_flags__irq_en_0_r,
  l2d__user_irq_en_flags__irq_en_1_r,
  l2d__user_irq_en_flags__irq_en_2_r,
  l2d__user_irq_en_flags__irq_en_3_r,
  l2d__user_irq_en_flags__irq_en_4_r,
  l2d__user_irq_en_flags__irq_en_5_r,
  l2d__user_irq_en_flags__irq_en_6_r,
  l2d__user_irq_en_flags__irq_en_7_r,
  l2d__user_irq_en_flags__irq_en_8_r,
  l2d__user_irq_en_flags__irq_en_9_r,
  l2d__user_irq_en_flags__irq_en_10_r,
  l2d__user_irq_en_flags__irq_en_11_r,
  l2d__user_irq_en_flags__irq_en_12_r,
  l2d__user_irq_en_flags__irq_en_13_r,
  l2d__user_irq_en_flags__irq_en_14_r,
  l2d__user_irq_en_flags__irq_en_15_r,
  l2d__user_cfg_regs__user_cfg_0_r,
  l2d__user_cfg_regs__user_cfg_1_r,
  l2d__user_cfg_regs__user_cfg_2_r,
  l2d__user_cfg_regs__user_cfg_3_r,
  l2d__user_stat_regs__user_stat_0_r,
  l2d__user_stat_regs__user_stat_1_r,
  l2d__user_stat_regs__user_stat_2_r,
  l2d__user_stat_regs__user_stat_3_r,
  l2d__user_stat_regs__user_stat_4_r,
  l2d__user_stat_regs__user_stat_5_r,

  d2h_dec_pio_trans_size,
  d2h_dec_pio_read_data,
  d2h_dec_pio_ack,
  d2h_dec_pio_nack,
  d2l__control_w,
  d2l__control_we,
  d2l__control_re,
  d2l__status_w,
  d2l__status_we,
  d2l__status_re,
  d2l__user_irq_status_w,
  d2l__user_irq_status_we,
  d2l__user_irq_status_re,
  d2l__user_irq_enable_w,
  d2l__user_irq_enable_we,
  d2l__user_irq_enable_re,
  d2l__user_irq_flags__irq_0_w,
  d2l__user_irq_flags__irq_0_we,
  d2l__user_irq_flags__irq_0_re,
  d2l__user_irq_flags__irq_1_w,
  d2l__user_irq_flags__irq_1_we,
  d2l__user_irq_flags__irq_1_re,
  d2l__user_irq_flags__irq_2_w,
  d2l__user_irq_flags__irq_2_we,
  d2l__user_irq_flags__irq_2_re,
  d2l__user_irq_flags__irq_3_w,
  d2l__user_irq_flags__irq_3_we,
  d2l__user_irq_flags__irq_3_re,
  d2l__user_irq_flags__irq_4_w,
  d2l__user_irq_flags__irq_4_we,
  d2l__user_irq_flags__irq_4_re,
  d2l__user_irq_flags__irq_5_w,
  d2l__user_irq_flags__irq_5_we,
  d2l__user_irq_flags__irq_5_re,
  d2l__user_irq_flags__irq_6_w,
  d2l__user_irq_flags__irq_6_we,
  d2l__user_irq_flags__irq_6_re,
  d2l__user_irq_flags__irq_7_w,
  d2l__user_irq_flags__irq_7_we,
  d2l__user_irq_flags__irq_7_re,
  d2l__user_irq_flags__irq_8_w,
  d2l__user_irq_flags__irq_8_we,
  d2l__user_irq_flags__irq_8_re,
  d2l__user_irq_flags__irq_9_w,
  d2l__user_irq_flags__irq_9_we,
  d2l__user_irq_flags__irq_9_re,
  d2l__user_irq_flags__irq_10_w,
  d2l__user_irq_flags__irq_10_we,
  d2l__user_irq_flags__irq_10_re,
  d2l__user_irq_flags__irq_11_w,
  d2l__user_irq_flags__irq_11_we,
  d2l__user_irq_flags__irq_11_re,
  d2l__user_irq_flags__irq_12_w,
  d2l__user_irq_flags__irq_12_we,
  d2l__user_irq_flags__irq_12_re,
  d2l__user_irq_flags__irq_13_w,
  d2l__user_irq_flags__irq_13_we,
  d2l__user_irq_flags__irq_13_re,
  d2l__user_irq_flags__irq_14_w,
  d2l__user_irq_flags__irq_14_we,
  d2l__user_irq_flags__irq_14_re,
  d2l__user_irq_flags__irq_15_w,
  d2l__user_irq_flags__irq_15_we,
  d2l__user_irq_flags__irq_15_re,
  d2l__user_irq_en_flags__irq_en_0_w,
  d2l__user_irq_en_flags__irq_en_0_we,
  d2l__user_irq_en_flags__irq_en_0_re,
  d2l__user_irq_en_flags__irq_en_1_w,
  d2l__user_irq_en_flags__irq_en_1_we,
  d2l__user_irq_en_flags__irq_en_1_re,
  d2l__user_irq_en_flags__irq_en_2_w,
  d2l__user_irq_en_flags__irq_en_2_we,
  d2l__user_irq_en_flags__irq_en_2_re,
  d2l__user_irq_en_flags__irq_en_3_w,
  d2l__user_irq_en_flags__irq_en_3_we,
  d2l__user_irq_en_flags__irq_en_3_re,
  d2l__user_irq_en_flags__irq_en_4_w,
  d2l__user_irq_en_flags__irq_en_4_we,
  d2l__user_irq_en_flags__irq_en_4_re,
  d2l__user_irq_en_flags__irq_en_5_w,
  d2l__user_irq_en_flags__irq_en_5_we,
  d2l__user_irq_en_flags__irq_en_5_re,
  d2l__user_irq_en_flags__irq_en_6_w,
  d2l__user_irq_en_flags__irq_en_6_we,
  d2l__user_irq_en_flags__irq_en_6_re,
  d2l__user_irq_en_flags__irq_en_7_w,
  d2l__user_irq_en_flags__irq_en_7_we,
  d2l__user_irq_en_flags__irq_en_7_re,
  d2l__user_irq_en_flags__irq_en_8_w,
  d2l__user_irq_en_flags__irq_en_8_we,
  d2l__user_irq_en_flags__irq_en_8_re,
  d2l__user_irq_en_flags__irq_en_9_w,
  d2l__user_irq_en_flags__irq_en_9_we,
  d2l__user_irq_en_flags__irq_en_9_re,
  d2l__user_irq_en_flags__irq_en_10_w,
  d2l__user_irq_en_flags__irq_en_10_we,
  d2l__user_irq_en_flags__irq_en_10_re,
  d2l__user_irq_en_flags__irq_en_11_w,
  d2l__user_irq_en_flags__irq_en_11_we,
  d2l__user_irq_en_flags__irq_en_11_re,
  d2l__user_irq_en_flags__irq_en_12_w,
  d2l__user_irq_en_flags__irq_en_12_we,
  d2l__user_irq_en_flags__irq_en_12_re,
  d2l__user_irq_en_flags__irq_en_13_w,
  d2l__user_irq_en_flags__irq_en_13_we,
  d2l__user_irq_en_flags__irq_en_13_re,
  d2l__user_irq_en_flags__irq_en_14_w,
  d2l__user_irq_en_flags__irq_en_14_we,
  d2l__user_irq_en_flags__irq_en_14_re,
  d2l__user_irq_en_flags__irq_en_15_w,
  d2l__user_irq_en_flags__irq_en_15_we,
  d2l__user_irq_en_flags__irq_en_15_re,
  d2l__user_cfg_regs__user_cfg_0_w,
  d2l__user_cfg_regs__user_cfg_0_we,
  d2l__user_cfg_regs__user_cfg_0_re,
  d2l__user_cfg_regs__user_cfg_1_w,
  d2l__user_cfg_regs__user_cfg_1_we,
  d2l__user_cfg_regs__user_cfg_1_re,
  d2l__user_cfg_regs__user_cfg_2_w,
  d2l__user_cfg_regs__user_cfg_2_we,
  d2l__user_cfg_regs__user_cfg_2_re,
  d2l__user_cfg_regs__user_cfg_3_w,
  d2l__user_cfg_regs__user_cfg_3_we,
  d2l__user_cfg_regs__user_cfg_3_re,
  d2l__user_stat_regs__user_stat_0_w,
  d2l__user_stat_regs__user_stat_0_we,
  d2l__user_stat_regs__user_stat_0_re,
  d2l__user_stat_regs__user_stat_1_w,
  d2l__user_stat_regs__user_stat_1_we,
  d2l__user_stat_regs__user_stat_1_re,
  d2l__user_stat_regs__user_stat_2_w,
  d2l__user_stat_regs__user_stat_2_we,
  d2l__user_stat_regs__user_stat_2_re,
  d2l__user_stat_regs__user_stat_3_w,
  d2l__user_stat_regs__user_stat_3_we,
  d2l__user_stat_regs__user_stat_3_re,
  d2l__user_stat_regs__user_stat_4_w,
  d2l__user_stat_regs__user_stat_4_we,
  d2l__user_stat_regs__user_stat_4_re,
  d2l__user_stat_regs__user_stat_5_w,
  d2l__user_stat_regs__user_stat_5_we,
  d2l__user_stat_regs__user_stat_5_re );

  //------- inputs
  input    clk;
  input    sig_reset_n;
  input     [8:0] h2d_pio_dec_address;
  input     [15:0] h2d_pio_dec_write_data;
  input    h2d_pio_dec_trans_size;
  input    h2d_pio_dec_write;
  input    h2d_pio_dec_read;
  input     [15:0] l2d__control_r;
  input     [15:0] l2d__status_r;
  input     [15:0] l2d__user_irq_status_r;
  input     [15:0] l2d__user_irq_enable_r;
  input     [15:0] l2d__user_irq_flags__irq_0_r;
  input     [15:0] l2d__user_irq_flags__irq_1_r;
  input     [15:0] l2d__user_irq_flags__irq_2_r;
  input     [15:0] l2d__user_irq_flags__irq_3_r;
  input     [15:0] l2d__user_irq_flags__irq_4_r;
  input     [15:0] l2d__user_irq_flags__irq_5_r;
  input     [15:0] l2d__user_irq_flags__irq_6_r;
  input     [15:0] l2d__user_irq_flags__irq_7_r;
  input     [15:0] l2d__user_irq_flags__irq_8_r;
  input     [15:0] l2d__user_irq_flags__irq_9_r;
  input     [15:0] l2d__user_irq_flags__irq_10_r;
  input     [15:0] l2d__user_irq_flags__irq_11_r;
  input     [15:0] l2d__user_irq_flags__irq_12_r;
  input     [15:0] l2d__user_irq_flags__irq_13_r;
  input     [15:0] l2d__user_irq_flags__irq_14_r;
  input     [15:0] l2d__user_irq_flags__irq_15_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_0_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_1_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_2_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_3_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_4_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_5_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_6_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_7_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_8_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_9_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_10_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_11_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_12_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_13_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_14_r;
  input     [15:0] l2d__user_irq_en_flags__irq_en_15_r;
  input     [15:0] l2d__user_cfg_regs__user_cfg_0_r;
  input     [15:0] l2d__user_cfg_regs__user_cfg_1_r;
  input     [15:0] l2d__user_cfg_regs__user_cfg_2_r;
  input     [15:0] l2d__user_cfg_regs__user_cfg_3_r;
  input     [15:0] l2d__user_stat_regs__user_stat_0_r;
  input     [15:0] l2d__user_stat_regs__user_stat_1_r;
  input     [15:0] l2d__user_stat_regs__user_stat_2_r;
  input     [15:0] l2d__user_stat_regs__user_stat_3_r;
  input     [15:0] l2d__user_stat_regs__user_stat_4_r;
  input     [15:0] l2d__user_stat_regs__user_stat_5_r;

  //------- outputs
  output    d2h_dec_pio_trans_size;
  output     [15:0] d2h_dec_pio_read_data;
  output    d2h_dec_pio_ack;
  output    d2h_dec_pio_nack;
  output     [15:0] d2l__control_w;
  output    d2l__control_we;
  output    d2l__control_re;
  output     [15:0] d2l__status_w;
  output    d2l__status_we;
  output    d2l__status_re;
  output     [15:0] d2l__user_irq_status_w;
  output    d2l__user_irq_status_we;
  output    d2l__user_irq_status_re;
  output     [15:0] d2l__user_irq_enable_w;
  output    d2l__user_irq_enable_we;
  output    d2l__user_irq_enable_re;
  output     [15:0] d2l__user_irq_flags__irq_0_w;
  output    d2l__user_irq_flags__irq_0_we;
  output    d2l__user_irq_flags__irq_0_re;
  output     [15:0] d2l__user_irq_flags__irq_1_w;
  output    d2l__user_irq_flags__irq_1_we;
  output    d2l__user_irq_flags__irq_1_re;
  output     [15:0] d2l__user_irq_flags__irq_2_w;
  output    d2l__user_irq_flags__irq_2_we;
  output    d2l__user_irq_flags__irq_2_re;
  output     [15:0] d2l__user_irq_flags__irq_3_w;
  output    d2l__user_irq_flags__irq_3_we;
  output    d2l__user_irq_flags__irq_3_re;
  output     [15:0] d2l__user_irq_flags__irq_4_w;
  output    d2l__user_irq_flags__irq_4_we;
  output    d2l__user_irq_flags__irq_4_re;
  output     [15:0] d2l__user_irq_flags__irq_5_w;
  output    d2l__user_irq_flags__irq_5_we;
  output    d2l__user_irq_flags__irq_5_re;
  output     [15:0] d2l__user_irq_flags__irq_6_w;
  output    d2l__user_irq_flags__irq_6_we;
  output    d2l__user_irq_flags__irq_6_re;
  output     [15:0] d2l__user_irq_flags__irq_7_w;
  output    d2l__user_irq_flags__irq_7_we;
  output    d2l__user_irq_flags__irq_7_re;
  output     [15:0] d2l__user_irq_flags__irq_8_w;
  output    d2l__user_irq_flags__irq_8_we;
  output    d2l__user_irq_flags__irq_8_re;
  output     [15:0] d2l__user_irq_flags__irq_9_w;
  output    d2l__user_irq_flags__irq_9_we;
  output    d2l__user_irq_flags__irq_9_re;
  output     [15:0] d2l__user_irq_flags__irq_10_w;
  output    d2l__user_irq_flags__irq_10_we;
  output    d2l__user_irq_flags__irq_10_re;
  output     [15:0] d2l__user_irq_flags__irq_11_w;
  output    d2l__user_irq_flags__irq_11_we;
  output    d2l__user_irq_flags__irq_11_re;
  output     [15:0] d2l__user_irq_flags__irq_12_w;
  output    d2l__user_irq_flags__irq_12_we;
  output    d2l__user_irq_flags__irq_12_re;
  output     [15:0] d2l__user_irq_flags__irq_13_w;
  output    d2l__user_irq_flags__irq_13_we;
  output    d2l__user_irq_flags__irq_13_re;
  output     [15:0] d2l__user_irq_flags__irq_14_w;
  output    d2l__user_irq_flags__irq_14_we;
  output    d2l__user_irq_flags__irq_14_re;
  output     [15:0] d2l__user_irq_flags__irq_15_w;
  output    d2l__user_irq_flags__irq_15_we;
  output    d2l__user_irq_flags__irq_15_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_0_w;
  output    d2l__user_irq_en_flags__irq_en_0_we;
  output    d2l__user_irq_en_flags__irq_en_0_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_1_w;
  output    d2l__user_irq_en_flags__irq_en_1_we;
  output    d2l__user_irq_en_flags__irq_en_1_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_2_w;
  output    d2l__user_irq_en_flags__irq_en_2_we;
  output    d2l__user_irq_en_flags__irq_en_2_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_3_w;
  output    d2l__user_irq_en_flags__irq_en_3_we;
  output    d2l__user_irq_en_flags__irq_en_3_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_4_w;
  output    d2l__user_irq_en_flags__irq_en_4_we;
  output    d2l__user_irq_en_flags__irq_en_4_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_5_w;
  output    d2l__user_irq_en_flags__irq_en_5_we;
  output    d2l__user_irq_en_flags__irq_en_5_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_6_w;
  output    d2l__user_irq_en_flags__irq_en_6_we;
  output    d2l__user_irq_en_flags__irq_en_6_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_7_w;
  output    d2l__user_irq_en_flags__irq_en_7_we;
  output    d2l__user_irq_en_flags__irq_en_7_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_8_w;
  output    d2l__user_irq_en_flags__irq_en_8_we;
  output    d2l__user_irq_en_flags__irq_en_8_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_9_w;
  output    d2l__user_irq_en_flags__irq_en_9_we;
  output    d2l__user_irq_en_flags__irq_en_9_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_10_w;
  output    d2l__user_irq_en_flags__irq_en_10_we;
  output    d2l__user_irq_en_flags__irq_en_10_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_11_w;
  output    d2l__user_irq_en_flags__irq_en_11_we;
  output    d2l__user_irq_en_flags__irq_en_11_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_12_w;
  output    d2l__user_irq_en_flags__irq_en_12_we;
  output    d2l__user_irq_en_flags__irq_en_12_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_13_w;
  output    d2l__user_irq_en_flags__irq_en_13_we;
  output    d2l__user_irq_en_flags__irq_en_13_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_14_w;
  output    d2l__user_irq_en_flags__irq_en_14_we;
  output    d2l__user_irq_en_flags__irq_en_14_re;
  output     [15:0] d2l__user_irq_en_flags__irq_en_15_w;
  output    d2l__user_irq_en_flags__irq_en_15_we;
  output    d2l__user_irq_en_flags__irq_en_15_re;
  output     [15:0] d2l__user_cfg_regs__user_cfg_0_w;
  output    d2l__user_cfg_regs__user_cfg_0_we;
  output    d2l__user_cfg_regs__user_cfg_0_re;
  output     [15:0] d2l__user_cfg_regs__user_cfg_1_w;
  output    d2l__user_cfg_regs__user_cfg_1_we;
  output    d2l__user_cfg_regs__user_cfg_1_re;
  output     [15:0] d2l__user_cfg_regs__user_cfg_2_w;
  output    d2l__user_cfg_regs__user_cfg_2_we;
  output    d2l__user_cfg_regs__user_cfg_2_re;
  output     [15:0] d2l__user_cfg_regs__user_cfg_3_w;
  output    d2l__user_cfg_regs__user_cfg_3_we;
  output    d2l__user_cfg_regs__user_cfg_3_re;
  output     [15:0] d2l__user_stat_regs__user_stat_0_w;
  output    d2l__user_stat_regs__user_stat_0_we;
  output    d2l__user_stat_regs__user_stat_0_re;
  output     [15:0] d2l__user_stat_regs__user_stat_1_w;
  output    d2l__user_stat_regs__user_stat_1_we;
  output    d2l__user_stat_regs__user_stat_1_re;
  output     [15:0] d2l__user_stat_regs__user_stat_2_w;
  output    d2l__user_stat_regs__user_stat_2_we;
  output    d2l__user_stat_regs__user_stat_2_re;
  output     [15:0] d2l__user_stat_regs__user_stat_3_w;
  output    d2l__user_stat_regs__user_stat_3_we;
  output    d2l__user_stat_regs__user_stat_3_re;
  output     [15:0] d2l__user_stat_regs__user_stat_4_w;
  output    d2l__user_stat_regs__user_stat_4_we;
  output    d2l__user_stat_regs__user_stat_4_re;
  output     [15:0] d2l__user_stat_regs__user_stat_5_w;
  output    d2l__user_stat_regs__user_stat_5_we;
  output    d2l__user_stat_regs__user_stat_5_re;


  //------- wire defines
  wire   [8:0] pio_dec_address;
  wire   [15:0] pio_dec_write_data;
  wire  pio_dec_trans_size;
  wire  pio_dec_read;
  wire  pio_dec_write;
  
  //------- reg defines
  reg   [15:0] d2l__control_w;
  reg  d2l__control_we;
  reg  d2l__control_re;
  reg   [15:0] d2l__status_w;
  reg  d2l__status_we;
  reg  d2l__status_re;
  reg   [15:0] d2l__user_irq_status_w;
  reg  d2l__user_irq_status_we;
  reg  d2l__user_irq_status_re;
  reg   [15:0] d2l__user_irq_enable_w;
  reg  d2l__user_irq_enable_we;
  reg  d2l__user_irq_enable_re;
  reg   [15:0] d2l__user_irq_flags__irq_0_w;
  reg  d2l__user_irq_flags__irq_0_we;
  reg  d2l__user_irq_flags__irq_0_re;
  reg   [15:0] d2l__user_irq_flags__irq_1_w;
  reg  d2l__user_irq_flags__irq_1_we;
  reg  d2l__user_irq_flags__irq_1_re;
  reg   [15:0] d2l__user_irq_flags__irq_2_w;
  reg  d2l__user_irq_flags__irq_2_we;
  reg  d2l__user_irq_flags__irq_2_re;
  reg   [15:0] d2l__user_irq_flags__irq_3_w;
  reg  d2l__user_irq_flags__irq_3_we;
  reg  d2l__user_irq_flags__irq_3_re;
  reg   [15:0] d2l__user_irq_flags__irq_4_w;
  reg  d2l__user_irq_flags__irq_4_we;
  reg  d2l__user_irq_flags__irq_4_re;
  reg   [15:0] d2l__user_irq_flags__irq_5_w;
  reg  d2l__user_irq_flags__irq_5_we;
  reg  d2l__user_irq_flags__irq_5_re;
  reg   [15:0] d2l__user_irq_flags__irq_6_w;
  reg  d2l__user_irq_flags__irq_6_we;
  reg  d2l__user_irq_flags__irq_6_re;
  reg   [15:0] d2l__user_irq_flags__irq_7_w;
  reg  d2l__user_irq_flags__irq_7_we;
  reg  d2l__user_irq_flags__irq_7_re;
  reg   [15:0] d2l__user_irq_flags__irq_8_w;
  reg  d2l__user_irq_flags__irq_8_we;
  reg  d2l__user_irq_flags__irq_8_re;
  reg   [15:0] d2l__user_irq_flags__irq_9_w;
  reg  d2l__user_irq_flags__irq_9_we;
  reg  d2l__user_irq_flags__irq_9_re;
  reg   [15:0] d2l__user_irq_flags__irq_10_w;
  reg  d2l__user_irq_flags__irq_10_we;
  reg  d2l__user_irq_flags__irq_10_re;
  reg   [15:0] d2l__user_irq_flags__irq_11_w;
  reg  d2l__user_irq_flags__irq_11_we;
  reg  d2l__user_irq_flags__irq_11_re;
  reg   [15:0] d2l__user_irq_flags__irq_12_w;
  reg  d2l__user_irq_flags__irq_12_we;
  reg  d2l__user_irq_flags__irq_12_re;
  reg   [15:0] d2l__user_irq_flags__irq_13_w;
  reg  d2l__user_irq_flags__irq_13_we;
  reg  d2l__user_irq_flags__irq_13_re;
  reg   [15:0] d2l__user_irq_flags__irq_14_w;
  reg  d2l__user_irq_flags__irq_14_we;
  reg  d2l__user_irq_flags__irq_14_re;
  reg   [15:0] d2l__user_irq_flags__irq_15_w;
  reg  d2l__user_irq_flags__irq_15_we;
  reg  d2l__user_irq_flags__irq_15_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_0_w;
  reg  d2l__user_irq_en_flags__irq_en_0_we;
  reg  d2l__user_irq_en_flags__irq_en_0_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_1_w;
  reg  d2l__user_irq_en_flags__irq_en_1_we;
  reg  d2l__user_irq_en_flags__irq_en_1_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_2_w;
  reg  d2l__user_irq_en_flags__irq_en_2_we;
  reg  d2l__user_irq_en_flags__irq_en_2_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_3_w;
  reg  d2l__user_irq_en_flags__irq_en_3_we;
  reg  d2l__user_irq_en_flags__irq_en_3_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_4_w;
  reg  d2l__user_irq_en_flags__irq_en_4_we;
  reg  d2l__user_irq_en_flags__irq_en_4_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_5_w;
  reg  d2l__user_irq_en_flags__irq_en_5_we;
  reg  d2l__user_irq_en_flags__irq_en_5_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_6_w;
  reg  d2l__user_irq_en_flags__irq_en_6_we;
  reg  d2l__user_irq_en_flags__irq_en_6_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_7_w;
  reg  d2l__user_irq_en_flags__irq_en_7_we;
  reg  d2l__user_irq_en_flags__irq_en_7_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_8_w;
  reg  d2l__user_irq_en_flags__irq_en_8_we;
  reg  d2l__user_irq_en_flags__irq_en_8_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_9_w;
  reg  d2l__user_irq_en_flags__irq_en_9_we;
  reg  d2l__user_irq_en_flags__irq_en_9_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_10_w;
  reg  d2l__user_irq_en_flags__irq_en_10_we;
  reg  d2l__user_irq_en_flags__irq_en_10_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_11_w;
  reg  d2l__user_irq_en_flags__irq_en_11_we;
  reg  d2l__user_irq_en_flags__irq_en_11_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_12_w;
  reg  d2l__user_irq_en_flags__irq_en_12_we;
  reg  d2l__user_irq_en_flags__irq_en_12_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_13_w;
  reg  d2l__user_irq_en_flags__irq_en_13_we;
  reg  d2l__user_irq_en_flags__irq_en_13_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_14_w;
  reg  d2l__user_irq_en_flags__irq_en_14_we;
  reg  d2l__user_irq_en_flags__irq_en_14_re;
  reg   [15:0] d2l__user_irq_en_flags__irq_en_15_w;
  reg  d2l__user_irq_en_flags__irq_en_15_we;
  reg  d2l__user_irq_en_flags__irq_en_15_re;
  reg   [15:0] d2l__user_cfg_regs__user_cfg_0_w;
  reg  d2l__user_cfg_regs__user_cfg_0_we;
  reg  d2l__user_cfg_regs__user_cfg_0_re;
  reg   [15:0] d2l__user_cfg_regs__user_cfg_1_w;
  reg  d2l__user_cfg_regs__user_cfg_1_we;
  reg  d2l__user_cfg_regs__user_cfg_1_re;
  reg   [15:0] d2l__user_cfg_regs__user_cfg_2_w;
  reg  d2l__user_cfg_regs__user_cfg_2_we;
  reg  d2l__user_cfg_regs__user_cfg_2_re;
  reg   [15:0] d2l__user_cfg_regs__user_cfg_3_w;
  reg  d2l__user_cfg_regs__user_cfg_3_we;
  reg  d2l__user_cfg_regs__user_cfg_3_re;
  reg   [15:0] d2l__user_stat_regs__user_stat_0_w;
  reg  d2l__user_stat_regs__user_stat_0_we;
  reg  d2l__user_stat_regs__user_stat_0_re;
  reg   [15:0] d2l__user_stat_regs__user_stat_1_w;
  reg  d2l__user_stat_regs__user_stat_1_we;
  reg  d2l__user_stat_regs__user_stat_1_re;
  reg   [15:0] d2l__user_stat_regs__user_stat_2_w;
  reg  d2l__user_stat_regs__user_stat_2_we;
  reg  d2l__user_stat_regs__user_stat_2_re;
  reg   [15:0] d2l__user_stat_regs__user_stat_3_w;
  reg  d2l__user_stat_regs__user_stat_3_we;
  reg  d2l__user_stat_regs__user_stat_3_re;
  reg   [15:0] d2l__user_stat_regs__user_stat_4_w;
  reg  d2l__user_stat_regs__user_stat_4_we;
  reg  d2l__user_stat_regs__user_stat_4_re;
  reg   [15:0] d2l__user_stat_regs__user_stat_5_w;
  reg  d2l__user_stat_regs__user_stat_5_we;
  reg  d2l__user_stat_regs__user_stat_5_re;
  reg  pio_write_active;
  reg  pio_read_active;
  reg   [8:0] pio_dec_address_d1;
  reg   [15:0] pio_dec_write_data_d1;
  reg  pio_dec_trans_size_d1;
  reg  dec_pio_trans_size;
  reg  reg_width;
  reg   [15:0] dec_pio_read_data;
  reg   [15:0] dec_pio_read_data_d1;
  reg  dec_pio_ack;
  reg  dec_pio_nack;
  reg  dec_pio_ack_next;
  reg  dec_pio_nack_next;
  reg  pio_internal_ack;
  reg  pio_internal_nack;
  reg  pio_external_ack;
  reg  pio_external_nack;
  reg  pio_external_ack_next;
  reg  pio_external_nack_next;
  reg  pio_no_acks;
  reg  pio_activate_write;
  reg  pio_activate_read;
  reg   [15:0] dec_pio_read_data_next;
  reg  external_transaction_active;
  
  
  //------- assigns
  assign  pio_dec_address = h2d_pio_dec_address;
  assign  pio_dec_write_data = h2d_pio_dec_write_data;
  assign  pio_dec_trans_size = h2d_pio_dec_trans_size;
  assign  pio_dec_read = h2d_pio_dec_read;
  assign  pio_dec_write = h2d_pio_dec_write;
  assign  d2h_dec_pio_trans_size = dec_pio_trans_size;
  assign  d2h_dec_pio_read_data = dec_pio_read_data;
  assign  d2h_dec_pio_ack = dec_pio_ack;
  assign  d2h_dec_pio_nack = dec_pio_nack;
  
  //------- combinatorial assigns for pio read data
  always @ (*) begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end
  
  //------- reg assigns for pio read data
  always @ (posedge clk or negedge sig_reset_n) begin
    if (! sig_reset_n) begin
      dec_pio_read_data_d1 <= #1  16'b0;
    end
    else begin
      dec_pio_read_data_d1 <= #1 dec_pio_read_data_next;
    end
  end
  
  //------- reg assigns for pio i/f
  always @ (posedge clk or negedge sig_reset_n) begin
    if (! sig_reset_n) begin
      pio_write_active <= #1  1'b0;
      pio_read_active <= #1  1'b0;
      dec_pio_trans_size <= #1 1'b0;
    end
    else begin
      pio_write_active <= #1  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <= #1  pio_read_active ? pio_no_acks : pio_activate_read;
      dec_pio_trans_size <= #1 reg_width;
    end
    pio_dec_address_d1 <= #1   pio_dec_address;
    pio_dec_write_data_d1 <= #1  pio_dec_write_data;
    pio_dec_trans_size_d1 <= #1  pio_dec_trans_size;
  end
  
  //------- combinatorial assigns for pio ack/nack
  always @ (*) begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end
  
  //------- reg assigns for pio ack/nack
  always @ (posedge clk or negedge sig_reset_n) begin
    if (! sig_reset_n) begin
      dec_pio_ack <= #1 1'b0;
      dec_pio_nack <= #1 1'b0;
      pio_external_ack <= #1  1'b0;
      pio_external_nack <= #1  1'b0;
    end
    else begin
      dec_pio_ack <= #1 dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= #1 dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= #1 pio_external_ack_next;
      pio_external_nack <= #1 pio_external_nack_next;
    end
  end
  
  
  //------- address decode
  always @ (*) begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 16'b0;
    reg_width = 1'd0;
    
    d2l__control_w = pio_dec_write_data_d1  [15:0] ;
    d2l__control_we = 1'b0;
    d2l__control_re = 1'b0;
    d2l__status_w = pio_dec_write_data_d1  [15:0] ;
    d2l__status_we = 1'b0;
    d2l__status_re = 1'b0;
    d2l__user_irq_status_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_status_we = 1'b0;
    d2l__user_irq_status_re = 1'b0;
    d2l__user_irq_enable_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_enable_we = 1'b0;
    d2l__user_irq_enable_re = 1'b0;
    d2l__user_irq_flags__irq_0_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_0_we = 1'b0;
    d2l__user_irq_flags__irq_0_re = 1'b0;
    d2l__user_irq_flags__irq_1_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_1_we = 1'b0;
    d2l__user_irq_flags__irq_1_re = 1'b0;
    d2l__user_irq_flags__irq_2_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_2_we = 1'b0;
    d2l__user_irq_flags__irq_2_re = 1'b0;
    d2l__user_irq_flags__irq_3_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_3_we = 1'b0;
    d2l__user_irq_flags__irq_3_re = 1'b0;
    d2l__user_irq_flags__irq_4_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_4_we = 1'b0;
    d2l__user_irq_flags__irq_4_re = 1'b0;
    d2l__user_irq_flags__irq_5_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_5_we = 1'b0;
    d2l__user_irq_flags__irq_5_re = 1'b0;
    d2l__user_irq_flags__irq_6_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_6_we = 1'b0;
    d2l__user_irq_flags__irq_6_re = 1'b0;
    d2l__user_irq_flags__irq_7_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_7_we = 1'b0;
    d2l__user_irq_flags__irq_7_re = 1'b0;
    d2l__user_irq_flags__irq_8_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_8_we = 1'b0;
    d2l__user_irq_flags__irq_8_re = 1'b0;
    d2l__user_irq_flags__irq_9_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_9_we = 1'b0;
    d2l__user_irq_flags__irq_9_re = 1'b0;
    d2l__user_irq_flags__irq_10_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_10_we = 1'b0;
    d2l__user_irq_flags__irq_10_re = 1'b0;
    d2l__user_irq_flags__irq_11_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_11_we = 1'b0;
    d2l__user_irq_flags__irq_11_re = 1'b0;
    d2l__user_irq_flags__irq_12_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_12_we = 1'b0;
    d2l__user_irq_flags__irq_12_re = 1'b0;
    d2l__user_irq_flags__irq_13_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_13_we = 1'b0;
    d2l__user_irq_flags__irq_13_re = 1'b0;
    d2l__user_irq_flags__irq_14_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_14_we = 1'b0;
    d2l__user_irq_flags__irq_14_re = 1'b0;
    d2l__user_irq_flags__irq_15_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_flags__irq_15_we = 1'b0;
    d2l__user_irq_flags__irq_15_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_0_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_0_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_0_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_1_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_1_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_1_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_2_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_2_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_2_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_3_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_3_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_3_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_4_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_4_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_4_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_5_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_5_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_5_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_6_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_6_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_6_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_7_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_7_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_7_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_8_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_8_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_8_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_9_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_9_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_9_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_10_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_10_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_10_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_11_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_11_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_11_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_12_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_12_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_12_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_13_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_13_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_13_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_14_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_14_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_14_re = 1'b0;
    d2l__user_irq_en_flags__irq_en_15_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_irq_en_flags__irq_en_15_we = 1'b0;
    d2l__user_irq_en_flags__irq_en_15_re = 1'b0;
    d2l__user_cfg_regs__user_cfg_0_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_cfg_regs__user_cfg_0_we = 1'b0;
    d2l__user_cfg_regs__user_cfg_0_re = 1'b0;
    d2l__user_cfg_regs__user_cfg_1_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_cfg_regs__user_cfg_1_we = 1'b0;
    d2l__user_cfg_regs__user_cfg_1_re = 1'b0;
    d2l__user_cfg_regs__user_cfg_2_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_cfg_regs__user_cfg_2_we = 1'b0;
    d2l__user_cfg_regs__user_cfg_2_re = 1'b0;
    d2l__user_cfg_regs__user_cfg_3_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_cfg_regs__user_cfg_3_we = 1'b0;
    d2l__user_cfg_regs__user_cfg_3_re = 1'b0;
    d2l__user_stat_regs__user_stat_0_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_stat_regs__user_stat_0_we = 1'b0;
    d2l__user_stat_regs__user_stat_0_re = 1'b0;
    d2l__user_stat_regs__user_stat_1_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_stat_regs__user_stat_1_we = 1'b0;
    d2l__user_stat_regs__user_stat_1_re = 1'b0;
    d2l__user_stat_regs__user_stat_2_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_stat_regs__user_stat_2_we = 1'b0;
    d2l__user_stat_regs__user_stat_2_re = 1'b0;
    d2l__user_stat_regs__user_stat_3_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_stat_regs__user_stat_3_we = 1'b0;
    d2l__user_stat_regs__user_stat_3_re = 1'b0;
    d2l__user_stat_regs__user_stat_4_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_stat_regs__user_stat_4_we = 1'b0;
    d2l__user_stat_regs__user_stat_4_re = 1'b0;
    d2l__user_stat_regs__user_stat_5_w = pio_dec_write_data_d1  [15:0] ;
    d2l__user_stat_regs__user_stat_5_we = 1'b0;
    d2l__user_stat_regs__user_stat_5_re = 1'b0;
    
    casez(pio_dec_address_d1)
    //  Register: _control     Address: 0x0     External: false
    9'b00000000?:
      begin
        reg_width = 1'd1;
        d2l__control_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__control_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__control_r;
      end
    //  Register: _status     Address: 0x2     External: false
    9'b00000001?:
      begin
        reg_width = 1'd1;
        d2l__status_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__status_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__status_r;
      end
    //  Register: _user_irq_status     Address: 0x4     External: false
    9'b00000010?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_status_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_status_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_status_r;
      end
    //  Register: _user_irq_enable     Address: 0x6     External: false
    9'b00000011?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_enable_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_enable_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_enable_r;
      end
    //  Register: _user_irq_flags._irq_0     Address: 0x20     External: false
    9'b00010000?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_0_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_0_r;
      end
    //  Register: _user_irq_flags._irq_1     Address: 0x22     External: false
    9'b00010001?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_1_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_1_r;
      end
    //  Register: _user_irq_flags._irq_2     Address: 0x24     External: false
    9'b00010010?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_2_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_2_r;
      end
    //  Register: _user_irq_flags._irq_3     Address: 0x26     External: false
    9'b00010011?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_3_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_3_r;
      end
    //  Register: _user_irq_flags._irq_4     Address: 0x28     External: false
    9'b00010100?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_4_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_4_r;
      end
    //  Register: _user_irq_flags._irq_5     Address: 0x2a     External: false
    9'b00010101?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_5_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_5_r;
      end
    //  Register: _user_irq_flags._irq_6     Address: 0x2c     External: false
    9'b00010110?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_6_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_6_r;
      end
    //  Register: _user_irq_flags._irq_7     Address: 0x2e     External: false
    9'b00010111?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_7_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_7_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_7_r;
      end
    //  Register: _user_irq_flags._irq_8     Address: 0x30     External: false
    9'b00011000?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_8_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_8_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_8_r;
      end
    //  Register: _user_irq_flags._irq_9     Address: 0x32     External: false
    9'b00011001?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_9_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_9_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_9_r;
      end
    //  Register: _user_irq_flags._irq_10     Address: 0x34     External: false
    9'b00011010?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_10_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_10_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_10_r;
      end
    //  Register: _user_irq_flags._irq_11     Address: 0x36     External: false
    9'b00011011?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_11_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_11_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_11_r;
      end
    //  Register: _user_irq_flags._irq_12     Address: 0x38     External: false
    9'b00011100?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_12_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_12_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_12_r;
      end
    //  Register: _user_irq_flags._irq_13     Address: 0x3a     External: false
    9'b00011101?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_13_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_13_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_13_r;
      end
    //  Register: _user_irq_flags._irq_14     Address: 0x3c     External: false
    9'b00011110?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_14_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_14_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_14_r;
      end
    //  Register: _user_irq_flags._irq_15     Address: 0x3e     External: false
    9'b00011111?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_flags__irq_15_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_flags__irq_15_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_flags__irq_15_r;
      end
    //  Register: _user_irq_en_flags._irq_en_0     Address: 0x40     External: false
    9'b00100000?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_0_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_0_r;
      end
    //  Register: _user_irq_en_flags._irq_en_1     Address: 0x42     External: false
    9'b00100001?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_1_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_1_r;
      end
    //  Register: _user_irq_en_flags._irq_en_2     Address: 0x44     External: false
    9'b00100010?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_2_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_2_r;
      end
    //  Register: _user_irq_en_flags._irq_en_3     Address: 0x46     External: false
    9'b00100011?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_3_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_3_r;
      end
    //  Register: _user_irq_en_flags._irq_en_4     Address: 0x48     External: false
    9'b00100100?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_4_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_4_r;
      end
    //  Register: _user_irq_en_flags._irq_en_5     Address: 0x4a     External: false
    9'b00100101?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_5_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_5_r;
      end
    //  Register: _user_irq_en_flags._irq_en_6     Address: 0x4c     External: false
    9'b00100110?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_6_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_6_r;
      end
    //  Register: _user_irq_en_flags._irq_en_7     Address: 0x4e     External: false
    9'b00100111?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_7_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_7_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_7_r;
      end
    //  Register: _user_irq_en_flags._irq_en_8     Address: 0x50     External: false
    9'b00101000?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_8_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_8_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_8_r;
      end
    //  Register: _user_irq_en_flags._irq_en_9     Address: 0x52     External: false
    9'b00101001?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_9_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_9_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_9_r;
      end
    //  Register: _user_irq_en_flags._irq_en_10     Address: 0x54     External: false
    9'b00101010?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_10_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_10_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_10_r;
      end
    //  Register: _user_irq_en_flags._irq_en_11     Address: 0x56     External: false
    9'b00101011?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_11_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_11_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_11_r;
      end
    //  Register: _user_irq_en_flags._irq_en_12     Address: 0x58     External: false
    9'b00101100?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_12_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_12_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_12_r;
      end
    //  Register: _user_irq_en_flags._irq_en_13     Address: 0x5a     External: false
    9'b00101101?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_13_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_13_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_13_r;
      end
    //  Register: _user_irq_en_flags._irq_en_14     Address: 0x5c     External: false
    9'b00101110?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_14_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_14_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_14_r;
      end
    //  Register: _user_irq_en_flags._irq_en_15     Address: 0x5e     External: false
    9'b00101111?:
      begin
        reg_width = 1'd1;
        d2l__user_irq_en_flags__irq_en_15_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_irq_en_flags__irq_en_15_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_irq_en_flags__irq_en_15_r;
      end
    //  Register: _user_cfg_regs._user_cfg_0     Address: 0x80     External: false
    9'b01000000?:
      begin
        reg_width = 1'd1;
        d2l__user_cfg_regs__user_cfg_0_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_cfg_regs__user_cfg_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_cfg_regs__user_cfg_0_r;
      end
    //  Register: _user_cfg_regs._user_cfg_1     Address: 0x82     External: false
    9'b01000001?:
      begin
        reg_width = 1'd1;
        d2l__user_cfg_regs__user_cfg_1_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_cfg_regs__user_cfg_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_cfg_regs__user_cfg_1_r;
      end
    //  Register: _user_cfg_regs._user_cfg_2     Address: 0x84     External: false
    9'b01000010?:
      begin
        reg_width = 1'd1;
        d2l__user_cfg_regs__user_cfg_2_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_cfg_regs__user_cfg_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_cfg_regs__user_cfg_2_r;
      end
    //  Register: _user_cfg_regs._user_cfg_3     Address: 0x86     External: false
    9'b01000011?:
      begin
        reg_width = 1'd1;
        d2l__user_cfg_regs__user_cfg_3_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_cfg_regs__user_cfg_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_cfg_regs__user_cfg_3_r;
      end
    //  Register: _user_stat_regs._user_stat_0     Address: 0x100     External: false
    9'b10000000?:
      begin
        reg_width = 1'd1;
        d2l__user_stat_regs__user_stat_0_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_stat_regs__user_stat_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_stat_regs__user_stat_0_r;
      end
    //  Register: _user_stat_regs._user_stat_1     Address: 0x102     External: false
    9'b10000001?:
      begin
        reg_width = 1'd1;
        d2l__user_stat_regs__user_stat_1_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_stat_regs__user_stat_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_stat_regs__user_stat_1_r;
      end
    //  Register: _user_stat_regs._user_stat_2     Address: 0x104     External: false
    9'b10000010?:
      begin
        reg_width = 1'd1;
        d2l__user_stat_regs__user_stat_2_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_stat_regs__user_stat_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_stat_regs__user_stat_2_r;
      end
    //  Register: _user_stat_regs._user_stat_3     Address: 0x106     External: false
    9'b10000011?:
      begin
        reg_width = 1'd1;
        d2l__user_stat_regs__user_stat_3_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_stat_regs__user_stat_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_stat_regs__user_stat_3_r;
      end
    //  Register: _user_stat_regs._user_stat_4     Address: 0x108     External: false
    9'b10000100?:
      begin
        reg_width = 1'd1;
        d2l__user_stat_regs__user_stat_4_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_stat_regs__user_stat_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_stat_regs__user_stat_4_r;
      end
    //  Register: _user_stat_regs._user_stat_5     Address: 0x10a     External: false
    9'b10000101?:
      begin
        reg_width = 1'd1;
        d2l__user_stat_regs__user_stat_5_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l__user_stat_regs__user_stat_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [15:0]  = l2d__user_stat_regs__user_stat_5_r;
      end
    endcase
  end
  
endmodule

